export type FlagQuizCountry = {
  name: string;
  flagEmoji: string;
  countryCode: string;
  funFact: string;
};

export type FlagQuizQuestion = {
  correct: FlagQuizCountry;
  distractors: [FlagQuizCountry, FlagQuizCountry, FlagQuizCountry];
};

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function shuffleAndPickQuestions(count: number): FlagQuizQuestion[] {
  const shuffled = shuffle(FLAG_QUIZ_COUNTRIES);
  const selected = shuffled.slice(0, count);
  return selected.map((correct) => {
    const others = FLAG_QUIZ_COUNTRIES.filter((c) => c.countryCode !== correct.countryCode);
    const distractorPool = shuffle(others).slice(0, 3);
    return {
      correct,
      distractors: [distractorPool[0], distractorPool[1], distractorPool[2]] as [FlagQuizCountry, FlagQuizCountry, FlagQuizCountry],
    };
  });
}

export const FLAG_QUIZ_COUNTRIES: FlagQuizCountry[] = [
  // ── Americas ────────────────────────────────────────────────
  {
    name: "United States",
    flagEmoji: "\uD83C\uDDFA\uD83C\uDDF8",
    countryCode: "US",
    funFact: "The 50 stars on the US flag represent the 50 states, and the 13 stripes represent the original colonies.",
  },
  {
    name: "Canada",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDE6",
    countryCode: "CA",
    funFact: "Canada's maple leaf flag was adopted in 1965 — before that, Canada used a flag with the British Union Jack on it.",
  },
  {
    name: "Brazil",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDF7",
    countryCode: "BR",
    funFact: "Brazil's green and yellow flag has a blue globe with stars showing the night sky over Rio de Janeiro on November 15, 1889.",
  },
  {
    name: "Mexico",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDFD",
    countryCode: "MX",
    funFact: "Mexico's flag shows an eagle eating a snake on a cactus — this comes from an ancient Aztec legend about founding their city.",
  },
  {
    name: "Argentina",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDF7",
    countryCode: "AR",
    funFact: "Argentina's flag has a golden Sun of May in the center, representing the May Revolution of 1810.",
  },
  {
    name: "Jamaica",
    flagEmoji: "\uD83C\uDDEF\uD83C\uDDF2",
    countryCode: "JM",
    funFact: "Jamaica's flag is the only national flag that contains neither red, white, nor blue — it uses black, gold, and green.",
  },
  {
    name: "Peru",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDEA",
    countryCode: "PE",
    funFact: "Peru's red and white flag was designed by General Jose de San Martin, who was inspired by a flock of flamingos he saw flying.",
  },
  {
    name: "Colombia",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDF4",
    countryCode: "CO",
    funFact: "Colombia's yellow stripe is the widest because it represents gold — Colombia was known as El Dorado, the land of gold.",
  },
  {
    name: "Cuba",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDFA",
    countryCode: "CU",
    funFact: "Cuba's flag has a white star in a red triangle representing independence. The design was created in 1849 by a Cuban poet.",
  },
  {
    name: "Chile",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDF1",
    countryCode: "CL",
    funFact: "Chile's flag star is called the Lone Star and represents a guide for progress and honor. Its layout inspired the Texas state flag.",
  },
  {
    name: "Panama",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDE6",
    countryCode: "PA",
    funFact: "Panama's flag has four squares — the blue and red represent the two political parties, and the white represents the peace between them.",
  },
  {
    name: "Ecuador",
    flagEmoji: "\uD83C\uDDEA\uD83C\uDDE8",
    countryCode: "EC",
    funFact: "Ecuador's flag features the condor — the largest flying bird in the world — on its coat of arms.",
  },
  {
    name: "Guatemala",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDF9",
    countryCode: "GT",
    funFact: "Guatemala's flag has a quetzal bird, which is the national symbol. The quetzal was also used as currency by the ancient Maya.",
  },
  {
    name: "Belize",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDFF",
    countryCode: "BZ",
    funFact: "Belize's flag is one of the only national flags to feature humans — two men representing its mixed cultural heritage.",
  },
  {
    name: "Honduras",
    flagEmoji: "\uD83C\uDDED\uD83C\uDDF3",
    countryCode: "HN",
    funFact: "Honduras has five blue stars on its flag, one for each of the five Central American countries that once shared a union.",
  },
  {
    name: "El Salvador",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDFB",
    countryCode: "SV",
    funFact: "El Salvador's flag motto says 'God, Union, Liberty' — the same motto used by the old Central American Federation.",
  },
  {
    name: "Nicaragua",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDEE",
    countryCode: "NI",
    funFact: "Nicaragua's flag has a rainbow inside a triangle, representing peace and the country's bright future.",
  },
  {
    name: "Costa Rica",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDF7",
    countryCode: "CR",
    funFact: "Costa Rica's wide red stripe was added in 1848 — inspired by the French tricolor flag of the Revolution.",
  },
  {
    name: "Haiti",
    flagEmoji: "\uD83C\uDDED\uD83C\uDDF9",
    countryCode: "HT",
    funFact: "Haiti's blue and red flag was created by tearing the white from a French flag — symbolizing independence from France in 1804.",
  },
  {
    name: "Dominican Republic",
    flagEmoji: "\uD83C\uDDE9\uD83C\uDDF4",
    countryCode: "DO",
    funFact: "The Dominican Republic is one of the few countries whose flag features a Bible — it sits at the center of its coat of arms.",
  },
  {
    name: "Trinidad and Tobago",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDF9",
    countryCode: "TT",
    funFact: "Trinidad and Tobago's black diagonal stripe represents the islands' wealth and unity of the people working together.",
  },
  {
    name: "Barbados",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDE7",
    countryCode: "BB",
    funFact: "Barbados has a trident on its flag, but the handle is broken — symbolizing its break from colonial rule when it became independent in 1966.",
  },
  {
    name: "Bahamas",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDF8",
    countryCode: "BS",
    funFact: "The Bahamas flag's black triangle represents the people, the gold stripe is for the sunny beaches, and the blue stripes are for the sea.",
  },
  {
    name: "Antigua and Barbuda",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDEC",
    countryCode: "AG",
    funFact: "Antigua and Barbuda's rising sun has seven rays representing its six parishes plus Barbuda, rising over the sea.",
  },
  {
    name: "Dominica",
    flagEmoji: "\uD83C\uDDE9\uD83C\uDDF2",
    countryCode: "DM",
    funFact: "Dominica's flag features the Sisserou parrot — a rare purple parrot found only on this island, making it one of the very few flags with purple.",
  },
  {
    name: "Grenada",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDE9",
    countryCode: "GD",
    funFact: "Grenada's flag has a nutmeg on it because the island is one of the world's top producers of nutmeg spice.",
  },
  {
    name: "Saint Kitts and Nevis",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDF3",
    countryCode: "KN",
    funFact: "Saint Kitts and Nevis has two stars on its flag representing hope and liberty for its two islands.",
  },
  {
    name: "Saint Lucia",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDE8",
    countryCode: "LC",
    funFact: "Saint Lucia's flag features two triangular peaks — the Pitons — which are twin volcanic mountains on the island.",
  },
  {
    name: "Saint Vincent and the Grenadines",
    flagEmoji: "\uD83C\uDDFB\uD83C\uDDE8",
    countryCode: "VC",
    funFact: "Saint Vincent's three diamonds form a 'V' shape for Vincent — the country is nicknamed the 'Gems of the Antilles.'",
  },
  {
    name: "Venezuela",
    flagEmoji: "\uD83C\uDDFB\uD83C\uDDEA",
    countryCode: "VE",
    funFact: "Venezuela's flag has eight stars, one added in 2006 by President Chavez to honor the eight original provinces of the country.",
  },
  {
    name: "Guyana",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDFE",
    countryCode: "GY",
    funFact: "Guyana's flag is called the 'Golden Arrowhead' — the golden triangle points to the future and represents the country's mineral wealth.",
  },
  {
    name: "Suriname",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDF7",
    countryCode: "SR",
    funFact: "Suriname's green stripes stand for the forests that cover most of the country, and the yellow star represents unity and hope.",
  },
  {
    name: "Bolivia",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDF4",
    countryCode: "BO",
    funFact: "Bolivia has two official flags — the red, yellow, and green tricolor, and the Wiphala, a rainbow square pattern representing indigenous peoples.",
  },
  {
    name: "Paraguay",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDFE",
    countryCode: "PY",
    funFact: "Paraguay's flag is unique because it has different symbols on each side — the coat of arms on the front and the treasury seal on the back.",
  },
  {
    name: "Uruguay",
    flagEmoji: "\uD83C\uDDFA\uD83C\uDDFE",
    countryCode: "UY",
    funFact: "Uruguay's flag has nine stripes for its nine original departments, and a sun called the 'Sun of May' just like Argentina's flag.",
  },
  // ── Europe ──────────────────────────────────────────────────
  {
    name: "France",
    flagEmoji: "\uD83C\uDDEB\uD83C\uDDF7",
    countryCode: "FR",
    funFact: "France's blue, white, and red tricolor became famous during the French Revolution and inspired flags of many other countries.",
  },
  {
    name: "Germany",
    flagEmoji: "\uD83C\uDDE9\uD83C\uDDEA",
    countryCode: "DE",
    funFact: "Germany's black, red, and gold colors were worn by soldiers fighting Napoleon in the early 1800s.",
  },
  {
    name: "Italy",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF9",
    countryCode: "IT",
    funFact: "Italy's green, white, and red tricolor was inspired by the French flag. Napoleon introduced it when he conquered northern Italy.",
  },
  {
    name: "Spain",
    flagEmoji: "\uD83C\uDDEA\uD83C\uDDF8",
    countryCode: "ES",
    funFact: "Spain's red and yellow flag features a coat of arms showing the castles and lions of the kingdoms that united to form Spain.",
  },
  {
    name: "United Kingdom",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDE7",
    countryCode: "GB",
    funFact: "The UK's Union Jack combines three crosses: St George's cross for England, St Andrew's for Scotland, and St Patrick's for Ireland.",
  },
  {
    name: "Portugal",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDF9",
    countryCode: "PT",
    funFact: "Portugal's flag has an armillary sphere — a navigation tool — because Portugal was a great seafaring nation.",
  },
  {
    name: "Netherlands",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDF1",
    countryCode: "NL",
    funFact: "The Dutch flag was the first tricolor flag in the world and inspired many other national flags, including France's.",
  },
  {
    name: "Switzerland",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDED",
    countryCode: "CH",
    funFact: "Switzerland has one of only two square national flags in the world. The other is Vatican City.",
  },
  {
    name: "Sweden",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDEA",
    countryCode: "SE",
    funFact: "Sweden's blue and gold flag is one of the oldest in the world, with designs going back to at least the 1500s.",
  },
  {
    name: "Norway",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDF4",
    countryCode: "NO",
    funFact: "Norway's flag contains the flags of Iceland, Denmark, Finland, and Sweden hidden within its cross design.",
  },
  {
    name: "Denmark",
    flagEmoji: "\uD83C\uDDE9\uD83C\uDDF0",
    countryCode: "DK",
    funFact: "Denmark's Dannebrog is the oldest national flag still in use — it has been flown since the 13th century.",
  },
  {
    name: "Greece",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDF7",
    countryCode: "GR",
    funFact: "Greece's nine blue and white stripes represent the nine syllables of the phrase 'Freedom or Death' from the Greek revolution.",
  },
  {
    name: "Poland",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDF1",
    countryCode: "PL",
    funFact: "Poland's white and red colors come from the white eagle on a red background that has been Poland's symbol for over 700 years.",
  },
  {
    name: "Ireland",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDEA",
    countryCode: "IE",
    funFact: "Ireland's green represents the Gaelic tradition, white represents peace, and orange represents the Protestant minority.",
  },
  {
    name: "Austria",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDF9",
    countryCode: "AT",
    funFact: "Austria's red-white-red flag is one of the oldest in the world. Legend says a duke's white coat turned red from battle blood except under his belt.",
  },
  {
    name: "Belgium",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDEA",
    countryCode: "BE",
    funFact: "Belgium's black, yellow, and red flag was inspired by the 1789 French Revolution and taken from the colors of the Duchy of Brabant.",
  },
  {
    name: "Finland",
    flagEmoji: "\uD83C\uDDEB\uD83C\uDDEE",
    countryCode: "FI",
    funFact: "Finland's blue cross on white represents the country's thousands of lakes (blue) and winter snow (white).",
  },
  {
    name: "Iceland",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF8",
    countryCode: "IS",
    funFact: "Iceland's flag red cross represents fire from its many volcanoes, the white stands for the glaciers, and blue for the sea.",
  },
  {
    name: "Czech Republic",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDFF",
    countryCode: "CZ",
    funFact: "The Czech Republic added a blue triangle to its flag to tell it apart from Poland's similar red-and-white design.",
  },
  {
    name: "Hungary",
    flagEmoji: "\uD83C\uDDED\uD83C\uDDFA",
    countryCode: "HU",
    funFact: "Hungary's red, white, and green horizontal tricolor was adopted during the 1848 revolution inspired by the French tricolor.",
  },
  {
    name: "Ukraine",
    flagEmoji: "\uD83C\uDDFA\uD83C\uDDE6",
    countryCode: "UA",
    funFact: "Ukraine's blue over yellow flag represents a blue sky over golden wheat fields — the country is one of the world's biggest wheat producers.",
  },
  {
    name: "Russia",
    flagEmoji: "\uD83C\uDDF7\uD83C\uDDFA",
    countryCode: "RU",
    funFact: "Russia's white, blue, and red tricolor was first used by Tsar Peter the Great in the 1600s when building the Russian navy.",
  },
  {
    name: "Albania",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDF1",
    countryCode: "AL",
    funFact: "Albania's double-headed black eagle on a red background has been a symbol since the Middle Ages and comes from Byzantine heraldry.",
  },
  {
    name: "Andorra",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDE9",
    countryCode: "AD",
    funFact: "Andorra is one of the smallest countries in Europe, nestled in the mountains between France and Spain, and its flag blends both neighbors' colors.",
  },
  {
    name: "Armenia",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDF2",
    countryCode: "AM",
    funFact: "Armenia's red, blue, and orange tricolor was first used in the 5th century. Orange represents the creative spirit of the Armenian people.",
  },
  {
    name: "Azerbaijan",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDFF",
    countryCode: "AZ",
    funFact: "Azerbaijan's flag has a crescent and an eight-pointed star — the eight points represent the eight branches of the Turkic people.",
  },
  {
    name: "Bosnia and Herzegovina",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDE6",
    countryCode: "BA",
    funFact: "Bosnia's blue flag with a yellow triangle and white stars was designed to represent the three main ethnic groups living in the country.",
  },
  {
    name: "Belarus",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDFE",
    countryCode: "BY",
    funFact: "Belarus has a decorative red-and-white pattern on its flag called an ornament — it represents Belarusian folk art and crafts.",
  },
  {
    name: "Bulgaria",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDEC",
    countryCode: "BG",
    funFact: "Bulgaria's white, green, and red tricolor was inspired by the Russian flag when Russia helped Bulgaria gain independence in 1878.",
  },
  {
    name: "Cyprus",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDFE",
    countryCode: "CY",
    funFact: "Cyprus has a map of the island on its flag — one of only a few countries in the world to show its own geographic shape.",
  },
  {
    name: "Estonia",
    flagEmoji: "\uD83C\uDDEA\uD83C\uDDEA",
    countryCode: "EE",
    funFact: "Estonia's blue, black, and white flag represents the sky, dark past hardships, and hope for a bright future.",
  },
  {
    name: "Georgia",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDEA",
    countryCode: "GE",
    funFact: "Georgia's flag has five crosses — one large central cross and four smaller ones in each corner, known as the 'Five Cross Flag.'",
  },
  {
    name: "Croatia",
    flagEmoji: "\uD83C\uDDED\uD83C\uDDF7",
    countryCode: "HR",
    funFact: "Croatia's checkered coat of arms is one of the most recognizable in the world and has been used since medieval times.",
  },
  {
    name: "Liechtenstein",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDEE",
    countryCode: "LI",
    funFact: "Liechtenstein discovered at the 1936 Olympics that its flag was identical to Haiti's, so it added a golden crown to tell them apart.",
  },
  {
    name: "Lithuania",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDF9",
    countryCode: "LT",
    funFact: "Lithuania's yellow, green, and red flag represents the sun and grain (yellow), forests (green), and the blood of those who fought for freedom (red).",
  },
  {
    name: "Luxembourg",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDFA",
    countryCode: "LU",
    funFact: "Luxembourg's flag looks almost identical to the Netherlands flag but the blue stripe is lighter — a shade called 'azure blue.'",
  },
  {
    name: "Latvia",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDFB",
    countryCode: "LV",
    funFact: "Latvia's dark red (maroon) flag is one of the oldest national flag designs in the world, dating back to the 13th century.",
  },
  {
    name: "Monaco",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDE8",
    countryCode: "MC",
    funFact: "Monaco's red and white flag is almost identical to Indonesia's, but Monaco's is a perfect square while Indonesia's is a rectangle.",
  },
  {
    name: "Moldova",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDE9",
    countryCode: "MD",
    funFact: "Moldova's flag has a coat of arms in the center showing an eagle holding a golden cross, an olive branch, and a scepter.",
  },
  {
    name: "Montenegro",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDEA",
    countryCode: "ME",
    funFact: "Montenegro means 'Black Mountain' in Italian, and its golden flag with a red border represents the country's royal heritage.",
  },
  {
    name: "North Macedonia",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDF0",
    countryCode: "MK",
    funFact: "North Macedonia's flag has a golden sun with eight rays spreading to the edges — it is called the Sun of Liberty.",
  },
  {
    name: "Malta",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDF9",
    countryCode: "MT",
    funFact: "Malta's flag has a George Cross in the top corner — awarded by King George VI for the island's bravery during World War II.",
  },
  {
    name: "Romania",
    flagEmoji: "\uD83C\uDDF7\uD83C\uDDF4",
    countryCode: "RO",
    funFact: "Romania's blue, yellow, and red vertical tricolor is almost identical to Chad's — the two countries have had a long-standing dispute about it.",
  },
  {
    name: "Serbia",
    flagEmoji: "\uD83C\uDDF7\uD83C\uDDF8",
    countryCode: "RS",
    funFact: "Serbia's flag features a double-headed eagle, a symbol used by the old Serbian kingdom dating back to the medieval period.",
  },
  {
    name: "Slovakia",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDF0",
    countryCode: "SK",
    funFact: "Slovakia's flag has a double cross on three hills — the cross is a Christian symbol and the hills represent three mountain ranges.",
  },
  {
    name: "Slovenia",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDEE",
    countryCode: "SI",
    funFact: "Slovenia's flag has Mount Triglav — the country's highest mountain — on its coat of arms, surrounded by blue waves for the Adriatic Sea.",
  },
  {
    name: "San Marino",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDF2",
    countryCode: "SM",
    funFact: "San Marino claims to be the world's oldest republic, founded in 301 AD — its flag features three towers built on a mountain.",
  },
  {
    name: "Vatican City",
    flagEmoji: "\uD83C\uDDFB\uD83C\uDDE6",
    countryCode: "VA",
    funFact: "Vatican City is the world's smallest country and is home to the Pope. Its yellow and white square flag is unique in shape.",
  },
  // ── Africa ──────────────────────────────────────────────────
  {
    name: "South Africa",
    flagEmoji: "\uD83C\uDDFF\uD83C\uDDE6",
    countryCode: "ZA",
    funFact: "South Africa's colorful flag adopted in 1994 represents the coming together of its many peoples after apartheid ended.",
  },
  {
    name: "Kenya",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDEA",
    countryCode: "KE",
    funFact: "Kenya's flag features a Maasai warrior's shield and two crossed spears, representing the defense of freedom.",
  },
  {
    name: "Ghana",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDED",
    countryCode: "GH",
    funFact: "Ghana's flag has a black star at the center — it is called the Lodestar of African Freedom and inspired many African flags.",
  },
  {
    name: "Ethiopia",
    flagEmoji: "\uD83C\uDDEA\uD83C\uDDF9",
    countryCode: "ET",
    funFact: "Ethiopia's green, yellow, and red colors inspired Pan-Africanism and were adopted by dozens of African nations.",
  },
  {
    name: "Morocco",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDE6",
    countryCode: "MA",
    funFact: "Morocco's red flag with a green pentagram star is one of the oldest flags in the world, with roots going back to the 1600s.",
  },
  {
    name: "Nigeria",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDEC",
    countryCode: "NG",
    funFact: "Nigeria's simple green and white flag was designed by a student, Michael Taiwo Akinkunmi, in a competition in 1959.",
  },
  {
    name: "Egypt",
    flagEmoji: "\uD83C\uDDEA\uD83C\uDDEC",
    countryCode: "EG",
    funFact: "Egypt's flag features the Eagle of Saladin — a golden eagle used as a symbol by the great 12th-century Muslim leader.",
  },
  {
    name: "Tanzania",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDFF",
    countryCode: "TZ",
    funFact: "Tanzania's diagonal black stripe with gold edges represents the country's mineral wealth, including gold and diamonds.",
  },
  {
    name: "Rwanda",
    flagEmoji: "\uD83C\uDDF7\uD83C\uDDFC",
    countryCode: "RW",
    funFact: "Rwanda redesigned its flag in 2001 to move away from symbols of the 1994 genocide toward hope — shown by the sun in the top right.",
  },
  {
    name: "Angola",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDF4",
    countryCode: "AO",
    funFact: "Angola's flag has a machete and a cogwheel — representing farmers and workers — crossed over each other like a hammer and sickle.",
  },
  {
    name: "Burkina Faso",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDEB",
    countryCode: "BF",
    funFact: "Burkina Faso means 'Land of Incorruptible People' in two local languages. Its flag has a yellow star representing the country's mineral wealth.",
  },
  {
    name: "Burundi",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDEE",
    countryCode: "BI",
    funFact: "Burundi's flag has three red stars outlined in green, representing the three main ethnic groups: the Hutu, Tutsi, and Twa peoples.",
  },
  {
    name: "Benin",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDEF",
    countryCode: "BJ",
    funFact: "Benin's green, yellow, and red flag returned in 1990 after the country ended its communist government and restored the original design.",
  },
  {
    name: "Botswana",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDFC",
    countryCode: "BW",
    funFact: "Botswana is famous for its zebras, and the country's blue and black flag with a white stripe was inspired by these striped animals.",
  },
  {
    name: "DR Congo",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDE9",
    countryCode: "CD",
    funFact: "The Democratic Republic of Congo's flag has a red diagonal stripe edged in yellow — representing the blood of the country's martyrs.",
  },
  {
    name: "Central African Republic",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDEB",
    countryCode: "CF",
    funFact: "The Central African Republic's four horizontal stripes are cut by a vertical red stripe, with a gold star symbolizing independence.",
  },
  {
    name: "Republic of the Congo",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDEC",
    countryCode: "CG",
    funFact: "Congo's diagonal green, yellow, and red stripes were inspired by the Pan-African colors that represented freedom across the continent.",
  },
  {
    name: "Ivory Coast",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDEE",
    countryCode: "CI",
    funFact: "Ivory Coast's orange, white, and green flag is the mirror image of Ireland's flag — same colors, just flipped left to right.",
  },
  {
    name: "Cameroon",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDF2",
    countryCode: "CM",
    funFact: "Cameroon's flag has a gold star in the center called the Star of Unity, representing the coming together of French and English-speaking regions.",
  },
  {
    name: "Cabo Verde",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDFB",
    countryCode: "CV",
    funFact: "Cabo Verde's ten stars represent its ten main islands in the Atlantic Ocean off the coast of West Africa.",
  },
  {
    name: "Djibouti",
    flagEmoji: "\uD83C\uDDE9\uD83C\uDDEF",
    countryCode: "DJ",
    funFact: "Djibouti's light blue and green flag has a red star inside a white triangle, representing the unity of its two main ethnic groups.",
  },
  {
    name: "Algeria",
    flagEmoji: "\uD83C\uDDE9\uD83C\uDDFF",
    countryCode: "DZ",
    funFact: "Algeria's green and white flag with a red crescent and star represents Islam, and green symbolizes the beauty of nature.",
  },
  {
    name: "Eritrea",
    flagEmoji: "\uD83C\uDDEA\uD83C\uDDF7",
    countryCode: "ER",
    funFact: "Eritrea's flag has an olive wreath from its old UN flag on a green triangle — representing the victory of its independence movement.",
  },
  {
    name: "Gabon",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDE6",
    countryCode: "GA",
    funFact: "Gabon's green, yellow, and blue stripes represent the forests, the equator sun, and the sea. It removed the French tricolor in 1960.",
  },
  {
    name: "Gambia",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDF2",
    countryCode: "GM",
    funFact: "Gambia's flag has a blue stripe representing the Gambia River, which flows through the entire tiny country from east to west.",
  },
  {
    name: "Guinea",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDF3",
    countryCode: "GN",
    funFact: "Guinea's red, yellow, and green tricolor was directly inspired by the French flag but uses Pan-African colors instead.",
  },
  {
    name: "Equatorial Guinea",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDF6",
    countryCode: "GQ",
    funFact: "Equatorial Guinea's flag has a silk cotton tree in the center — this type of tree is where the country's first treaty was signed.",
  },
  {
    name: "Guinea-Bissau",
    flagEmoji: "\uD83C\uDDEC\uD83C\uDDFC",
    countryCode: "GW",
    funFact: "Guinea-Bissau's flag has a black star like Ghana's — both stars symbolize African freedom and were inspired by the same Pan-African movement.",
  },
  {
    name: "Comoros",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDF2",
    countryCode: "KM",
    funFact: "Comoros has four stars and four green stripes on its flag, each one representing one of its four islands in the Indian Ocean.",
  },
  {
    name: "Lesotho",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDF8",
    countryCode: "LS",
    funFact: "Lesotho's flag has a Basotho hat called a mokorotlo — it is the only country with a hat on its flag.",
  },
  {
    name: "Liberia",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDF7",
    countryCode: "LR",
    funFact: "Liberia's flag looks like the US flag with one star, because it was founded by freed American slaves who brought American traditions with them.",
  },
  {
    name: "Libya",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDFE",
    countryCode: "LY",
    funFact: "Libya has one of the simplest flags in the world — just a plain black, red, and green tricolor with a white crescent and star.",
  },
  {
    name: "Madagascar",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDEC",
    countryCode: "MG",
    funFact: "Madagascar's white and red stripes come from the colors of the Merina Kingdom that once ruled the island, with green for the coastal peoples.",
  },
  {
    name: "Mali",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDF1",
    countryCode: "ML",
    funFact: "Mali's green, gold, and red tricolor uses Pan-African colors. Mali was once home to one of the greatest empires in African history.",
  },
  {
    name: "Mauritania",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDF7",
    countryCode: "MR",
    funFact: "Mauritania added two red stripes to its flag in 2017, representing the blood shed defending the country — the only flag change after a referendum.",
  },
  {
    name: "Mauritius",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDFA",
    countryCode: "MU",
    funFact: "Mauritius has four horizontal stripes in red, blue, yellow, and green — representing independence, the Indian Ocean, sunshine, and vegetation.",
  },
  {
    name: "Malawi",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDFC",
    countryCode: "MW",
    funFact: "Malawi's flag has a rising red sun, which was added in 2010 to show the dawn of a new era — though the older design was later restored.",
  },
  {
    name: "Mozambique",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDFF",
    countryCode: "MZ",
    funFact: "Mozambique's flag is the only national flag with a modern firearm on it — an AK-47 with a bayonet, representing the defense of independence.",
  },
  {
    name: "Namibia",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDE6",
    countryCode: "NA",
    funFact: "Namibia's golden sun has 12 rays, and the diagonal stripes represent the country's people, resources, and the Namib Desert.",
  },
  {
    name: "Niger",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDEA",
    countryCode: "NE",
    funFact: "Niger's orange and white stripes with a green stripe and an orange circle represent the Sahara Desert, purity, and fertile land.",
  },
  {
    name: "Seychelles",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDE8",
    countryCode: "SC",
    funFact: "Seychelles has the most colorful flag in the world — five rays of blue, yellow, red, white, and green spreading from the bottom left corner.",
  },
  {
    name: "Sudan",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDE9",
    countryCode: "SD",
    funFact: "Sudan's flag uses Pan-Arab colors (red, white, black) with a green triangle representing Islam and the country's agricultural wealth.",
  },
  {
    name: "Sierra Leone",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDF1",
    countryCode: "SL",
    funFact: "Sierra Leone's three equal green, white, and blue stripes represent the mountains, unity, and the Atlantic Ocean coastline.",
  },
  {
    name: "Senegal",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDF3",
    countryCode: "SN",
    funFact: "Senegal's green star in the center represents the hope of the people — the star was added at independence in 1960.",
  },
  {
    name: "Somalia",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDF4",
    countryCode: "SO",
    funFact: "Somalia's five-pointed star represents the five regions where Somali people live across the Horn of Africa.",
  },
  {
    name: "South Sudan",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDF8",
    countryCode: "SS",
    funFact: "South Sudan became the world's newest country in 2011. Its flag has a gold star inside a blue triangle, representing the Nile River.",
  },
  {
    name: "Sao Tome and Principe",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDF9",
    countryCode: "ST",
    funFact: "Sao Tome and Principe's flag has two black stars representing its two islands — tiny volcanic islands in the Gulf of Guinea.",
  },
  {
    name: "Eswatini",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDFF",
    countryCode: "SZ",
    funFact: "Eswatini (formerly Swaziland) has a Nguni shield and two spears at the center — symbols of the Swazi people's warrior culture.",
  },
  {
    name: "Chad",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDE9",
    countryCode: "TD",
    funFact: "Chad's blue, yellow, and red flag is almost identical to Romania's flag. Chad's blue is slightly darker, but it is very hard to tell apart.",
  },
  {
    name: "Togo",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDEC",
    countryCode: "TG",
    funFact: "Togo's five stripes represent its five regions, and the red square with a white star stands for fidelity and purity.",
  },
  {
    name: "Tunisia",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDF3",
    countryCode: "TN",
    funFact: "Tunisia's red flag with a crescent and star inside a white circle is one of the most recognizable in North Africa.",
  },
  {
    name: "Uganda",
    flagEmoji: "\uD83C\uDDFA\uD83C\uDDEC",
    countryCode: "UG",
    funFact: "Uganda's flag features the grey crowned crane, the national bird. This elegant bird can dance and was named Uganda's symbol for its grace.",
  },
  {
    name: "Zambia",
    flagEmoji: "\uD83C\uDDFF\uD83C\uDDF2",
    countryCode: "ZM",
    funFact: "Zambia's flag has a flying eagle in the bottom right corner — representing freedom — set against stripes of green, red, black, and orange.",
  },
  {
    name: "Zimbabwe",
    flagEmoji: "\uD83C\uDDFF\uD83C\uDDFC",
    countryCode: "ZW",
    funFact: "Zimbabwe's flag has a Zimbabwe Bird — an ancient soapstone carving — on a red star, representing the country's pre-colonial heritage.",
  },
  // ── Asia ────────────────────────────────────────────────────
  {
    name: "Japan",
    flagEmoji: "\uD83C\uDDEF\uD83C\uDDF5",
    countryCode: "JP",
    funFact: "Japan's Hinomaru, meaning 'circle of the sun,' is one of the simplest national flags and has been used for over 1,000 years.",
  },
  {
    name: "China",
    flagEmoji: "\uD83C\uDDE8\uD83C\uDDF3",
    countryCode: "CN",
    funFact: "China's flag has one large star and four small ones. The large star represents the Communist Party and the four small ones the Chinese people.",
  },
  {
    name: "India",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF3",
    countryCode: "IN",
    funFact: "India's flag has a navy blue wheel called the Ashoka Chakra with 24 spokes, representing the cycle of time and progress.",
  },
  {
    name: "South Korea",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDF7",
    countryCode: "KR",
    funFact: "South Korea's Taegukgi flag features symbols from ancient Korean philosophy representing heaven, earth, water, and fire.",
  },
  {
    name: "Thailand",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDED",
    countryCode: "TH",
    funFact: "Thailand's red, white, and blue flag was designed in 1917 when King Vajiravudh wanted to show solidarity with the Allied powers in WWI.",
  },
  {
    name: "Vietnam",
    flagEmoji: "\uD83C\uDDFB\uD83C\uDDF3",
    countryCode: "VN",
    funFact: "Vietnam's red flag with a yellow star has been used since 1945. The star's five points represent workers, farmers, soldiers, intellectuals, and youth.",
  },
  {
    name: "Indonesia",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDE9",
    countryCode: "ID",
    funFact: "Indonesia's red and white flag is known as Sang Saka Merah-Putih. Red symbolizes courage and white symbolizes purity.",
  },
  {
    name: "Malaysia",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDFE",
    countryCode: "MY",
    funFact: "Malaysia's 14 stripes and 14-pointed star represent its 13 states plus the federal government.",
  },
  {
    name: "Singapore",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDEC",
    countryCode: "SG",
    funFact: "Singapore's crescent moon and five stars represent a new nation on the rise, with the stars standing for democracy, peace, progress, justice, and equality.",
  },
  {
    name: "Pakistan",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDF0",
    countryCode: "PK",
    funFact: "Pakistan's green and white flag features a crescent and star. The white stripe represents the non-Muslim minorities of Pakistan.",
  },
  {
    name: "Turkey",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDF7",
    countryCode: "TR",
    funFact: "Turkey's red flag with a crescent and star is one of the oldest flag designs in the world — similar designs date back to the Ottoman Empire.",
  },
  {
    name: "Saudi Arabia",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDE6",
    countryCode: "SA",
    funFact: "Saudi Arabia's flag has Arabic writing that says the Islamic declaration of faith, making it one of the few flags with a religious text.",
  },
  {
    name: "Israel",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF1",
    countryCode: "IL",
    funFact: "Israel's flag features the Star of David and is based on the design of the Jewish prayer shawl called the tallit.",
  },
  {
    name: "Philippines",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDED",
    countryCode: "PH",
    funFact: "The Philippines' flag is the only one that is flipped upside down during wartime — when at war, the red stripe goes on top.",
  },
  {
    name: "Nepal",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDF5",
    countryCode: "NP",
    funFact: "Nepal is the only country in the world with a non-rectangular national flag — it is made of two stacked triangles.",
  },
  {
    name: "Sri Lanka",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDF0",
    countryCode: "LK",
    funFact: "Sri Lanka's flag features a golden lion holding a sword — this lion has been a royal symbol on the island for over 2,500 years.",
  },
  {
    name: "Bangladesh",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDE9",
    countryCode: "BD",
    funFact: "Bangladesh's red disc on green is placed slightly left of center — so when the flag waves, the disc appears centered.",
  },
  {
    name: "United Arab Emirates",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDEA",
    countryCode: "AE",
    funFact: "The UAE's flag colors represent Arab unity — green for prosperity, white for peace, black for oil wealth, and red for strength.",
  },
  {
    name: "Jordan",
    flagEmoji: "\uD83C\uDDEF\uD83C\uDDF4",
    countryCode: "JO",
    funFact: "Jordan's flag has a small white seven-pointed star on a red triangle — the seven points represent the seven verses of the opening of the Quran.",
  },
  {
    name: "Afghanistan",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDEB",
    countryCode: "AF",
    funFact: "Afghanistan's flag has changed more than 20 times in the last 100 years — more than almost any other country in the world.",
  },
  {
    name: "Bahrain",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDED",
    countryCode: "BH",
    funFact: "Bahrain's flag has a zigzag edge with five white triangles, representing the five pillars of Islam.",
  },
  {
    name: "Brunei",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDF3",
    countryCode: "BN",
    funFact: "Brunei's flag has a royal crest with a parasol — a symbol of royalty — and a crescent. Brunei is still ruled by a Sultan.",
  },
  {
    name: "Bhutan",
    flagEmoji: "\uD83C\uDDE7\uD83C\uDDF9",
    countryCode: "BT",
    funFact: "Bhutan means 'Land of the Thunder Dragon,' and its flag features a white dragon holding jewels representing wealth and perfection.",
  },
  {
    name: "Iraq",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF6",
    countryCode: "IQ",
    funFact: "Iraq's flag has Arabic calligraphy in the center reading 'God is Great' — added in 1991 in a handwritten style by Saddam Hussein.",
  },
  {
    name: "Iran",
    flagEmoji: "\uD83C\uDDEE\uD83C\uDDF7",
    countryCode: "IR",
    funFact: "Iran's flag has a stylized emblem of a tulip in the center — the tulip is a symbol of martyrdom in Persian culture.",
  },
  {
    name: "Kyrgyzstan",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDEC",
    countryCode: "KG",
    funFact: "Kyrgyzstan's flag shows the inside of a yurt — a traditional round tent — which is home to many nomadic people of Central Asia.",
  },
  {
    name: "Cambodia",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDED",
    countryCode: "KH",
    funFact: "Cambodia's flag shows Angkor Wat, the world's largest religious monument — it is the only national flag to feature a building.",
  },
  {
    name: "North Korea",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDF5",
    countryCode: "KP",
    funFact: "North Korea's flag has a red star inside a white circle on a blue-bordered red stripe — a design inspired by the Soviet Union's flag.",
  },
  {
    name: "Kuwait",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDFC",
    countryCode: "KW",
    funFact: "Kuwait's flag has a black trapezoid on the left side, representing the oil fields that made Kuwait one of the world's richest countries.",
  },
  {
    name: "Kazakhstan",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDFF",
    countryCode: "KZ",
    funFact: "Kazakhstan's light blue flag has a golden steppe eagle and a traditional sun pattern — blue represents the sky that nomads looked up to.",
  },
  {
    name: "Laos",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDE6",
    countryCode: "LA",
    funFact: "Laos is the only communist country whose flag does not have a star — instead it has a white circle representing the Mekong River's full moon.",
  },
  {
    name: "Lebanon",
    flagEmoji: "\uD83C\uDDF1\uD83C\uDDE7",
    countryCode: "LB",
    funFact: "Lebanon's flag features a cedar tree — the Cedar of Lebanon — which has been a symbol of the country for thousands of years.",
  },
  {
    name: "Myanmar",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDF2",
    countryCode: "MM",
    funFact: "Myanmar's flag has a large white star in the center on yellow, green, and red stripes, representing solidarity, tranquility, and courage.",
  },
  {
    name: "Mongolia",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDF3",
    countryCode: "MN",
    funFact: "Mongolia's flag has a golden symbol called the Soyombo — an ancient symbol that represents fire, sun, moon, earth, water, and the yin-yang.",
  },
  {
    name: "Maldives",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDFB",
    countryCode: "MV",
    funFact: "Maldives' green rectangle with a white crescent on red represents the coral reefs, Islamic faith, and the blood of national heroes.",
  },
  {
    name: "Oman",
    flagEmoji: "\uD83C\uDDF4\uD83C\uDDF2",
    countryCode: "OM",
    funFact: "Oman's national emblem has a Khanjar — a traditional curved dagger — crossed with two swords, representing the country's warrior heritage.",
  },
  {
    name: "Palestine",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDF8",
    countryCode: "PS",
    funFact: "Palestine's black, white, green, and red flag uses the Pan-Arab colors that have symbolized Arab unity since the early 20th century.",
  },
  {
    name: "Qatar",
    flagEmoji: "\uD83C\uDDF6\uD83C\uDDE6",
    countryCode: "QA",
    funFact: "Qatar's flag is maroon — not red — because the original dye from local plants turned red flags to a brownish-maroon color in the desert sun.",
  },
  {
    name: "Syria",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDFE",
    countryCode: "SY",
    funFact: "Syria's flag has two green stars in the center, representing Syria and Egypt — two countries that once united into one for three years.",
  },
  {
    name: "Tajikistan",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDEF",
    countryCode: "TJ",
    funFact: "Tajikistan's flag has a crown with seven stars above it — the crown represents the Tajik people and the stars stand for friendship.",
  },
  {
    name: "Timor-Leste",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDF1",
    countryCode: "TL",
    funFact: "Timor-Leste (East Timor) has a black triangle with a white star, representing the guiding light that led the people through the dark colonial past.",
  },
  {
    name: "Turkmenistan",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDF2",
    countryCode: "TM",
    funFact: "Turkmenistan's flag has the most complex carpet pattern of any national flag — five traditional carpet designs run down the left side.",
  },
  {
    name: "Uzbekistan",
    flagEmoji: "\uD83C\uDDFA\uD83C\uDDFF",
    countryCode: "UZ",
    funFact: "Uzbekistan's flag has a crescent and twelve stars, and three colors: blue for water and sky, white for peace, and green for nature.",
  },
  {
    name: "Yemen",
    flagEmoji: "\uD83C\uDDFE\uD83C\uDDEA",
    countryCode: "YE",
    funFact: "Yemen's red, white, and black tricolor uses Pan-Arab colors. Red stands for the blood of fighters, white for a bright future, and black for the past.",
  },
  // ── Oceania ────────────────────────────────────────────────
  {
    name: "Australia",
    flagEmoji: "\uD83C\uDDE6\uD83C\uDDFA",
    countryCode: "AU",
    funFact: "Australia's flag features the Southern Cross constellation, which can only be seen in the Southern Hemisphere.",
  },
  {
    name: "New Zealand",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDFF",
    countryCode: "NZ",
    funFact: "New Zealand's flag has four red stars making up the Southern Cross — one fewer star than Australia's version of the constellation.",
  },
  {
    name: "Fiji",
    flagEmoji: "\uD83C\uDDEB\uD83C\uDDEF",
    countryCode: "FJ",
    funFact: "Fiji's light blue flag reflects the Pacific Ocean that surrounds the islands, and features a British coat of arms with sugarcane and a lion.",
  },
  {
    name: "Papua New Guinea",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDEC",
    countryCode: "PG",
    funFact: "Papua New Guinea's flag has a bird of paradise — the raggiana bird — in flight, plus the Southern Cross constellation.",
  },
  {
    name: "Solomon Islands",
    flagEmoji: "\uD83C\uDDF8\uD83C\uDDE7",
    countryCode: "SB",
    funFact: "The Solomon Islands' five stars represent its five main island groups, and the blue and green represent the sea and land.",
  },
  {
    name: "Vanuatu",
    flagEmoji: "\uD83C\uDDFB\uD83C\uDDFA",
    countryCode: "VU",
    funFact: "Vanuatu's flag has a boar's tusk — a symbol of wealth and prosperity in local culture — inside a black triangle.",
  },
  {
    name: "Samoa",
    flagEmoji: "\uD83C\uDDFC\uD83C\uDDF8",
    countryCode: "WS",
    funFact: "Samoa's flag has five white stars of the Southern Cross on a red background, with a small white fifth star added in 1949.",
  },
  {
    name: "Kiribati",
    flagEmoji: "\uD83C\uDDF0\uD83C\uDDEE",
    countryCode: "KI",
    funFact: "Kiribati's flag shows a frigate bird flying over a rising sun above blue and white waves, representing life on the Pacific Ocean.",
  },
  {
    name: "Tonga",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDF4",
    countryCode: "TO",
    funFact: "Tonga's red flag with a white square and red cross comes from a Christian cross design that has been on the flag since the 1860s.",
  },
  {
    name: "Micronesia",
    flagEmoji: "\uD83C\uDDEB\uD83C\uDDF2",
    countryCode: "FM",
    funFact: "Micronesia's four stars on a blue background represent its four main island groups: Yap, Chuuk, Pohnpei, and Kosrae.",
  },
  {
    name: "Palau",
    flagEmoji: "\uD83C\uDDF5\uD83C\uDDFC",
    countryCode: "PW",
    funFact: "Palau's golden circle on light blue represents the moon — the moon is important to Palauans for fishing and farming schedules.",
  },
  {
    name: "Marshall Islands",
    flagEmoji: "\uD83C\uDDF2\uD83C\uDDED",
    countryCode: "MH",
    funFact: "The Marshall Islands' flag has a rising diagonal stripe of orange and white, with a large white star representing the cross-shaped island chain.",
  },
  {
    name: "Nauru",
    flagEmoji: "\uD83C\uDDF3\uD83C\uDDF7",
    countryCode: "NR",
    funFact: "Nauru's flag shows a gold stripe for the equator and a 12-pointed white star for its 12 original tribes — Nauru sits just south of the equator.",
  },
  {
    name: "Tuvalu",
    flagEmoji: "\uD83C\uDDF9\uD83C\uDDFB",
    countryCode: "TV",
    funFact: "Tuvalu's nine stars represent its nine inhabited islands. It is one of the lowest-lying countries on Earth and is threatened by rising seas.",
  },
];
