export type HangmanWord = {
  word: string;
  category: string;
  difficulty: 'easy' | 'hard';
  definition: string;
  usageExample: string;
  pronunciation: string;
  hint: string;
};

export const HANGMAN_WORDS: HangmanWord[] = [
  // ─── BEACH & OCEAN ────────────────────────────────────────────────────────────
  { word: 'WAVE', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A moving ridge of water on the surface of the sea.',
    usageExample: 'The big wave knocked me off my feet!',
    pronunciation: 'WAYV',
    hint: 'Water at the shore moves in and out like this' },
  { word: 'CORAL', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A hard colorful structure built by tiny sea creatures.',
    usageExample: 'We saw bright coral through our snorkel masks.',
    pronunciation: 'KOR-ul',
    hint: 'Colorful rock-like stuff that tiny sea creatures build' },
  { word: 'TIDE', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'The rise and fall of the ocean caused by the moon.',
    usageExample: 'At low tide, we found crabs in the rock pools.',
    pronunciation: 'TYD',
    hint: 'The moon pulls the ocean up and down twice a day' },
  { word: 'REEF', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A ridge of coral or rock just below the ocean surface.',
    usageExample: 'Hundreds of fish lived around the reef.',
    pronunciation: 'REEF',
    hint: 'An underwater ridge where fish love to hide and live' },
  { word: 'DUNE', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A hill of sand shaped by the wind.',
    usageExample: 'We ran down the tall sand dune to the beach.',
    pronunciation: 'DOON',
    hint: 'Wind piles up sand into hills near the beach' },
  { word: 'SHARK', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A large ocean fish known for its sharp teeth.',
    usageExample: 'The shark swam silently beneath the boat.',
    pronunciation: 'SHARK',
    hint: 'This ocean swimmer has a fin on its back' },
  { word: 'SURF', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'Waves breaking on a shore, or to ride those waves.',
    usageExample: 'She learned to surf on her first day at the beach.',
    pronunciation: 'SERF',
    hint: 'Grab a board and ride the breaking waves' },
  { word: 'PIER', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A platform built on stilts that extends out over the water.',
    usageExample: 'We fished off the end of the old wooden pier.',
    pronunciation: 'PEER',
    hint: 'A wooden walkway that sticks out over the water' },
  { word: 'BUOY', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A floating marker in the water that guides boats.',
    usageExample: 'The red buoy marked the safe swimming zone.',
    pronunciation: 'BOO-ee',
    hint: 'A floating bobber that marks something important in the water' },
  { word: 'CRAB', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A sea creature with a hard shell and big claws.',
    usageExample: 'A tiny crab scuttled across the wet sand.',
    pronunciation: 'KRAB',
    hint: 'It walks sideways and has claws' },
  { word: 'SNORKEL', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A tube you breathe through while floating face-down in water.',
    usageExample: 'With my snorkel I could see the fish below.',
    pronunciation: 'SNOR-kul',
    hint: 'A breathing tube for floating face-down in the water' },
  { word: 'STARFISH', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A star-shaped sea creature with five arms.',
    usageExample: 'We found a bright orange starfish in the tide pool.',
    pronunciation: 'STAR-fish',
    hint: 'You might find this in a tide pool' },
  { word: 'SEAGULL', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A grey and white bird that lives near the sea.',
    usageExample: 'A seagull stole a chip right from my hand!',
    pronunciation: 'SEE-gul',
    hint: 'A noisy beach bird famous for stealing snacks' },
  { word: 'OCEAN', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'The vast body of salt water that covers most of Earth.',
    usageExample: 'The ocean stretched all the way to the horizon.',
    pronunciation: 'OH-shun',
    hint: 'Salty water that covers most of the planet' },
  { word: 'COAST', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'The land that runs along the edge of the sea.',
    usageExample: 'We drove along the coast watching the waves.',
    pronunciation: 'KOHST',
    hint: 'Where the land meets the sea' },
  { word: 'KELP', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'A giant seaweed that grows in underwater forests.',
    usageExample: 'Sea otters wrap themselves in kelp to sleep.',
    pronunciation: 'KELP',
    hint: 'Giant underwater seaweed that makes a green forest' },
  { word: 'SHELL', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'The hard outer covering of a sea creature.',
    usageExample: 'She collected every shell she found on the beach.',
    pronunciation: 'SHEL',
    hint: 'A hard protective cover you find washed up on the beach' },
  { word: 'SAND', category: 'Beach & Ocean', difficulty: 'easy',
    definition: 'Tiny grains of crushed rock and shells found on beaches.',
    usageExample: 'The sand was so hot we had to wear flip flops.',
    pronunciation: 'SAND',
    hint: 'Tiny grains under your feet at the beach' },
  { word: 'JELLYFISH', category: 'Beach & Ocean', difficulty: 'hard',
    definition: 'A soft, see-through sea creature with long stinging tentacles.',
    usageExample: 'We spotted a jellyfish floating near the shore.',
    pronunciation: 'JEL-ee-fish',
    hint: 'See-through and wobbly with long stinging arms' },
  { word: 'SAILBOAT', category: 'Beach & Ocean', difficulty: 'hard',
    definition: 'A boat powered by the wind through large sails.',
    usageExample: 'A white sailboat glided quietly across the bay.',
    pronunciation: 'SAYL-boht',
    hint: 'A boat that moves using only the power of wind' },
  { word: 'SUNSCREEN', category: 'Beach & Ocean', difficulty: 'hard',
    definition: 'A cream you put on skin to protect it from the sun.',
    usageExample: 'Mom made us put sunscreen on before swimming.',
    pronunciation: 'SUN-skreen',
    hint: 'You rub this on before going to the beach' },
  { word: 'LIFEGUARD', category: 'Beach & Ocean', difficulty: 'hard',
    definition: 'A person trained to rescue swimmers in danger.',
    usageExample: 'The lifeguard blew her whistle when we swam too far.',
    pronunciation: 'LYF-gard',
    hint: 'This person watches swimmers from a tall chair at the beach' },
  { word: 'SANDCASTLE', category: 'Beach & Ocean', difficulty: 'hard',
    definition: 'A model of a castle built from wet sand on a beach.',
    usageExample: 'We spent an hour building the perfect sandcastle.',
    pronunciation: 'SAND-kas-ul',
    hint: 'You need wet sand and a bucket to build this' },
  { word: 'LIGHTHOUSE', category: 'Beach & Ocean', difficulty: 'hard',
    definition: 'A tall tower with a flashing light that guides ships safely.',
    usageExample: 'The lighthouse flashed every ten seconds through the fog.',
    pronunciation: 'LYT-howss',
    hint: 'A tall blinking tower that warns ships at night' },
  { word: 'SUNBURN', category: 'Beach & Ocean', difficulty: 'hard',
    definition: 'Red sore skin caused by too much sun.',
    usageExample: 'I forgot sunscreen and got a terrible sunburn.',
    pronunciation: 'SUN-bern',
    hint: 'Forget sunscreen and your skin turns red and sore' },

  // ─── MOUNTAINS & NATURE ───────────────────────────────────────────────────────
  { word: 'PEAK', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'The pointed top of a mountain.',
    usageExample: 'Snow covered the peak even in summer.',
    pronunciation: 'PEEK',
    hint: 'The very tippy top of a mountain' },
  { word: 'TRAIL', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A path through nature for walking or hiking.',
    usageExample: 'We followed the trail through the pine forest.',
    pronunciation: 'TRAYL',
    hint: 'A path for hikers to follow through nature' },
  { word: 'BISON', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A large shaggy wild animal also called a buffalo.',
    usageExample: 'A herd of bison blocked the road in Yellowstone.',
    pronunciation: 'BY-sun',
    hint: 'A huge shaggy wild animal sometimes called a buffalo' },
  { word: 'GEYSER', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A natural spring that shoots hot water into the air.',
    usageExample: 'Old Faithful is the most famous geyser in the world.',
    pronunciation: 'GY-zer',
    hint: 'A natural hot spring that shoots water into the air' },
  { word: 'CANYON', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A deep valley with steep rocky walls carved by a river.',
    usageExample: 'We stood at the edge of the canyon and looked down.',
    pronunciation: 'KAN-yun',
    hint: 'A very deep valley carved by a river over millions of years' },
  { word: 'BEAR', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A large powerful wild animal with thick fur and strong claws.',
    usageExample: 'We saw a black bear eating berries by the trail.',
    pronunciation: 'BAYR',
    hint: 'A large furry wild animal that loves honey and berries' },
  { word: 'HAWK', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A fast bird of prey with sharp eyesight and curved talons.',
    usageExample: 'A hawk circled high above the mountain looking for food.',
    pronunciation: 'HAWK',
    hint: 'A sharp-eyed hunting bird that circles high in the sky' },
  { word: 'VALLEY', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'Low land between hills or mountains, often with a river.',
    usageExample: 'The valley was green and full of wildflowers.',
    pronunciation: 'VAL-ee',
    hint: 'Low land that sits between two mountains' },
  { word: 'FOREST', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A large area of land covered with trees.',
    usageExample: 'We walked quietly through the dark pine forest.',
    pronunciation: 'FOR-est',
    hint: 'A big area covered with lots and lots of trees' },
  { word: 'PINE', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'An evergreen tree with needle-like leaves and pinecones.',
    usageExample: 'The pine trees smelled wonderful after the rain.',
    pronunciation: 'PYN',
    hint: 'An evergreen tree with needles and pinecones' },
  { word: 'WOLF', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A wild animal related to dogs that lives and hunts in packs.',
    usageExample: 'We heard a wolf howl in the distance at night.',
    pronunciation: 'WULF',
    hint: 'A wild dog that howls at the moon and hunts in packs' },
  { word: 'MOSS', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A soft green plant that grows on rocks and trees in damp places.',
    usageExample: 'The old rocks were covered in thick green moss.',
    pronunciation: 'MAWS',
    hint: 'Soft green carpet that grows on rocks and tree trunks' },
  { word: 'FERN', category: 'Mountains & Nature', difficulty: 'easy',
    definition: 'A leafy green plant that grows in shady forests.',
    usageExample: 'Giant ferns lined the path through the rainforest.',
    pronunciation: 'FERN',
    hint: 'A leafy plant that loves shady spots in the forest' },
  { word: 'GLACIER', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'A huge slow-moving river of ice that shapes the land.',
    usageExample: 'The glacier had carved the valley over thousands of years.',
    pronunciation: 'GLAY-sher',
    hint: 'Think frozen water slowly creeping down a mountain' },
  { word: 'SUMMIT', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'The very highest point of a mountain.',
    usageExample: 'It took six hours to reach the summit.',
    pronunciation: 'SUM-it',
    hint: 'The highest point you can reach on a mountain' },
  { word: 'BOULDER', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'A very large rock, often bigger than a person.',
    usageExample: 'We climbed up onto the giant boulder to see the view.',
    pronunciation: 'BOHL-der',
    hint: 'A rock so big a person can climb on top of it' },
  { word: 'CAMPFIRE', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'A fire made outdoors for warmth, cooking, or fun.',
    usageExample: 'We roasted marshmallows over the campfire.',
    pronunciation: 'KAMP-fyr',
    hint: 'You roast marshmallows over this at night outdoors' },
  { word: 'WATERFALL', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'Water flowing over the edge of a cliff into a pool below.',
    usageExample: 'The waterfall was so loud we had to shout.',
    pronunciation: 'WAW-ter-fawl',
    hint: 'Water falling off a cliff edge into a pool below' },
  { word: 'WILDFLOWER', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'A flower that grows naturally without being planted.',
    usageExample: 'The meadow was full of purple and yellow wildflowers.',
    pronunciation: 'WYLD-flow-er',
    hint: 'A flower no one planted — it just grows on its own' },
  { word: 'BINOCULARS', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'A tool you look through to see things far away up close.',
    usageExample: 'Dad used binoculars to spot the eagle in the tree.',
    pronunciation: 'bih-NOK-yoo-lerz',
    hint: 'Something you look through to see things far away' },
  { word: 'ELEVATION', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'How high a place is above sea level.',
    usageExample: 'At high elevation the air is thinner and colder.',
    pronunciation: 'el-eh-VAY-shun',
    hint: 'How high above sea level you are standing' },
  { word: 'AVALANCHE', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'A mass of snow and ice that suddenly slides down a mountain.',
    usageExample: 'The loud sound triggered an avalanche on the slope.',
    pronunciation: 'AV-uh-lanch',
    hint: 'A sudden rush of snow sliding down a mountain' },
  { word: 'WILDERNESS', category: 'Mountains & Nature', difficulty: 'hard',
    definition: 'A wild natural area untouched by people.',
    usageExample: 'We camped deep in the wilderness with no phone signal.',
    pronunciation: 'WIL-der-ness',
    hint: 'Wild land far from any roads or buildings' },

  // ─── DESERT & SOUTHWEST ───────────────────────────────────────────────────────
  { word: 'CACTUS', category: 'Desert & Southwest', difficulty: 'easy',
    definition: 'A spiky desert plant that stores water in its thick stem.',
    usageExample: 'The tall cactus stood alone in the red desert.',
    pronunciation: 'KAK-tus',
    hint: 'A spiky plant that stores water and loves the desert heat' },
  { word: 'MESA', category: 'Desert & Southwest', difficulty: 'easy',
    definition: 'A flat-topped hill with steep sides, common in deserts.',
    usageExample: 'We hiked to the top of the mesa to see the whole valley.',
    pronunciation: 'MAY-suh',
    hint: 'A flat-topped hill that rises above the desert floor' },
  { word: 'ADOBE', category: 'Desert & Southwest', difficulty: 'easy',
    definition: 'A type of building made from sun-dried clay bricks.',
    usageExample: 'The adobe house stayed cool even in the summer heat.',
    pronunciation: 'ah-DOH-bee',
    hint: 'Houses in the Southwest are made from this sun-dried clay' },
  { word: 'ARCH', category: 'Desert & Southwest', difficulty: 'easy',
    definition: 'A curved rock formation shaped like a doorway.',
    usageExample: 'We walked through the giant red rock arch.',
    pronunciation: 'ARCH',
    hint: 'A curved rock that forms a natural doorway' },
  { word: 'CLIFF', category: 'Desert & Southwest', difficulty: 'easy',
    definition: 'A steep, tall face of rock or earth.',
    usageExample: 'The cliff dropped straight down into the canyon below.',
    pronunciation: 'KLIF',
    hint: 'A steep wall of rock that drops straight down' },
  { word: 'DUST', category: 'Desert & Southwest', difficulty: 'easy',
    definition: 'Fine dry powder made of tiny particles of earth.',
    usageExample: 'Dust swirled up from the dirt road as we drove.',
    pronunciation: 'DUST',
    hint: 'Fine powder that blows in the dry desert wind' },
  { word: 'LIZARD', category: 'Desert & Southwest', difficulty: 'easy',
    definition: 'A scaly reptile with four legs that loves warm, dry places.',
    usageExample: 'A tiny lizard darted under a rock to hide from us.',
    pronunciation: 'LIZ-erd',
    hint: 'A scaly reptile that basks on warm rocks in the sun' },
  { word: 'CANYON', category: 'Desert & Southwest', difficulty: 'easy',
    definition: 'A deep narrow valley with steep rocky walls.',
    usageExample: 'We marveled at the layers of color inside the canyon.',
    pronunciation: 'KAN-yun',
    hint: 'A deep narrow valley with steep colorful rock walls' },
  { word: 'PUEBLO', category: 'Desert & Southwest', difficulty: 'hard',
    definition: 'A traditional Native American village made of adobe bricks stacked like apartments.',
    usageExample: 'The ancient pueblo had been home to people for over a thousand years.',
    pronunciation: 'PWEB-loh',
    hint: 'A traditional Native American village made from clay' },
  { word: 'SAGUARO', category: 'Desert & Southwest', difficulty: 'hard',
    definition: 'A very tall cactus with arms that only grows in the Sonoran Desert.',
    usageExample: 'The saguaro cactus was taller than our whole house.',
    pronunciation: 'suh-WAR-oh',
    hint: 'The giant cactus with arms you see in Arizona' },
  { word: 'ARROYO', category: 'Desert & Southwest', difficulty: 'hard',
    definition: 'A dry gully that fills with rushing water after heavy rain.',
    usageExample: 'We stayed back from the arroyo because a storm was coming.',
    pronunciation: 'uh-ROY-oh',
    hint: 'A dry ditch in the desert that floods fast when it rains' },
  { word: 'TURQUOISE', category: 'Desert & Southwest', difficulty: 'hard',
    definition: 'A blue-green stone used in Native American jewelry.',
    usageExample: 'She wore a beautiful turquoise bracelet from the market.',
    pronunciation: 'TER-kwoiz',
    hint: 'A blue-green stone used in Southwestern jewelry' },
  { word: 'SANDSTONE', category: 'Desert & Southwest', difficulty: 'hard',
    definition: 'A type of rock made from layers of sand pressed together over time.',
    usageExample: 'The red sandstone cliffs glowed orange in the sunset.',
    pronunciation: 'SAND-stohn',
    hint: 'Red rock made from layers of sand pressed hard over time' },
  { word: 'HOODOO', category: 'Desert & Southwest', difficulty: 'hard',
    definition: 'A tall thin spire of rock carved by wind and water over millions of years.',
    usageExample: 'Bryce Canyon is famous for its orange and red hoodoos.',
    pronunciation: 'HOO-doo',
    hint: 'A tall skinny rock spire shaped by wind and rain' },
  { word: 'PETROGLYPH', category: 'Desert & Southwest', difficulty: 'hard',
    definition: 'Ancient art carved into rock by people thousands of years ago.',
    usageExample: 'We found a petroglyph of a deer carved into the canyon wall.',
    pronunciation: 'PET-roh-glif',
    hint: 'Ancient drawings scratched into rock by people long ago' },
  { word: 'ROADRUNNER', category: 'Desert & Southwest', difficulty: 'hard',
    definition: 'A fast bird that lives in the desert and rarely flies.',
    usageExample: 'The roadrunner sprinted across the road faster than we expected.',
    pronunciation: 'ROHD-run-er',
    hint: 'A desert bird that runs faster than it flies' },

  // ─── HISTORY & LANDMARKS ──────────────────────────────────────────────────────
  { word: 'FLAG', category: 'History & Landmarks', difficulty: 'easy',
    definition: 'A piece of cloth with colors or symbols that represents a country.',
    usageExample: 'The flag flew high above the government building.',
    pronunciation: 'FLAG',
    hint: 'Colored cloth on a pole that stands for a country' },
  { word: 'FORT', category: 'History & Landmarks', difficulty: 'easy',
    definition: 'A strong building built to defend against enemies.',
    usageExample: 'Soldiers once lived and trained inside the old fort.',
    pronunciation: 'FORT',
    hint: 'A strong walled building that once protected soldiers' },
  { word: 'BELL', category: 'History & Landmarks', difficulty: 'easy',
    definition: 'A hollow metal object that rings when struck, often used in history.',
    usageExample: 'The Liberty Bell has a famous crack in it.',
    pronunciation: 'BEL',
    hint: 'A hollow metal thing that makes a ringing sound when struck' },
  { word: 'DOME', category: 'History & Landmarks', difficulty: 'easy',
    definition: 'A rounded roof shaped like the top half of a ball.',
    usageExample: 'The gold dome on the Capitol building shone in the sun.',
    pronunciation: 'DOHM',
    hint: 'A big rounded roof on top of an important building' },
  { word: 'STATUE', category: 'History & Landmarks', difficulty: 'easy',
    definition: 'A carved or molded figure of a person or animal.',
    usageExample: 'We stood at the base of the huge statue in the harbor.',
    pronunciation: 'STAT-yoo',
    hint: 'A large carved figure of a person or animal you can visit' },
  { word: 'MUSEUM', category: 'History & Landmarks', difficulty: 'easy',
    definition: 'A building where important objects and art are kept and shown.',
    usageExample: 'We spent the whole morning at the natural history museum.',
    pronunciation: 'myoo-ZEE-um',
    hint: 'A building full of art and history things to see' },
  { word: 'BRIDGE', category: 'History & Landmarks', difficulty: 'easy',
    definition: 'A structure built over a river or road so people can cross it.',
    usageExample: 'We walked across the famous old stone bridge.',
    pronunciation: 'BRIJ',
    hint: 'A structure that lets you cross over water or roads' },
  { word: 'CANNON', category: 'History & Landmarks', difficulty: 'easy',
    definition: 'A large old weapon that fires heavy metal balls.',
    usageExample: 'A row of cannons lined the walls of the old fort.',
    pronunciation: 'KAN-un',
    hint: 'An old weapon at forts that fired heavy metal balls' },
  { word: 'MONUMENT', category: 'History & Landmarks', difficulty: 'hard',
    definition: 'A structure built to honor an important person or event from history.',
    usageExample: 'We saw the Washington Monument reflected in the pool.',
    pronunciation: 'MON-yoo-ment',
    hint: 'A tall structure built to honor someone from history' },
  { word: 'MEMORIAL', category: 'History & Landmarks', difficulty: 'hard',
    definition: 'A place or object built to help people remember those who died.',
    usageExample: 'Families came to the memorial to honor the soldiers.',
    pronunciation: 'meh-MOR-ee-ul',
    hint: 'A place built to remember people who gave their lives' },
  { word: 'COLONIAL', category: 'History & Landmarks', difficulty: 'hard',
    definition: 'Relating to a time when one country ruled over another far away.',
    usageExample: 'The colonial buildings had big white columns at the front.',
    pronunciation: 'kuh-LOH-nee-ul',
    hint: 'From the time when one country ruled another far away' },
  { word: 'ARTIFACT', category: 'History & Landmarks', difficulty: 'hard',
    definition: 'An old object made by people from the past.',
    usageExample: 'The museum had an artifact from ancient Egypt.',
    pronunciation: 'AR-tih-fakt',
    hint: 'An old object made by people who lived long ago' },
  { word: 'LIBERTY', category: 'History & Landmarks', difficulty: 'hard',
    definition: 'The freedom to live and speak without being controlled.',
    usageExample: 'The Statue of Liberty stands for freedom for all people.',
    pronunciation: 'LIB-er-tee',
    hint: 'The freedom to live and speak as you choose' },
  { word: 'PATRIOT', category: 'History & Landmarks', difficulty: 'hard',
    definition: 'A person who loves and strongly supports their country.',
    usageExample: 'The patriots fought hard for their country\'s independence.',
    pronunciation: 'PAY-tree-ut',
    hint: 'Someone who loves their country and fights for it' },
  { word: 'BATTLEFIELD', category: 'History & Landmarks', difficulty: 'hard',
    definition: 'A place where a battle or war was fought in the past.',
    usageExample: 'We walked quietly across the old battlefield.',
    pronunciation: 'BAT-ul-feeld',
    hint: 'A field where a famous battle was once fought' },
  { word: 'CONSTITUTION', category: 'History & Landmarks', difficulty: 'hard',
    definition: 'The set of laws that a country is built on.',
    usageExample: 'The US Constitution was written over two hundred years ago.',
    pronunciation: 'kon-stih-TOO-shun',
    hint: 'The highest law of the land, written by the founders' },

  // ─── THEME PARKS & FUN ────────────────────────────────────────────────────────
  { word: 'RIDE', category: 'Theme Parks & Fun', difficulty: 'easy',
    definition: 'An exciting machine at a park that moves people around for fun.',
    usageExample: 'My favorite ride went through a dark tunnel.',
    pronunciation: 'RYD',
    hint: 'An exciting machine at a theme park that takes you on a thrill' },
  { word: 'QUEUE', category: 'Theme Parks & Fun', difficulty: 'easy',
    definition: 'A line of people waiting for something.',
    usageExample: 'We waited in the queue for twenty minutes.',
    pronunciation: 'KYOO',
    hint: 'A line of people all waiting for the same thing' },
  { word: 'SPIN', category: 'Theme Parks & Fun', difficulty: 'easy',
    definition: 'To turn around and around quickly.',
    usageExample: 'The teacup ride made us spin until we laughed.',
    pronunciation: 'SPIN',
    hint: 'Going round and round very fast' },
  { word: 'LOOP', category: 'Theme Parks & Fun', difficulty: 'easy',
    definition: 'A circular track where you go all the way upside down.',
    usageExample: 'The rollercoaster had a loop that flipped us upside down.',
    pronunciation: 'LOOP',
    hint: 'A track that takes you completely upside down' },
  { word: 'DROP', category: 'Theme Parks & Fun', difficulty: 'easy',
    definition: 'A sudden fall straight down, like on a drop tower ride.',
    usageExample: 'The big drop made everyone scream at the same time.',
    pronunciation: 'DROP',
    hint: 'A sudden plunge straight toward the ground on a ride' },
  { word: 'SHOW', category: 'Theme Parks & Fun', difficulty: 'easy',
    definition: 'A performance with music, characters, or fireworks.',
    usageExample: 'We watched the evening show from the front row.',
    pronunciation: 'SHOH',
    hint: 'A performance with music, lights, and characters at the park' },
  { word: 'PARADE', category: 'Theme Parks & Fun', difficulty: 'easy',
    definition: 'A march with floats, music, and characters through a park.',
    usageExample: 'The parade came down Main Street with dancers and music.',
    pronunciation: 'puh-RAYD',
    hint: 'A moving celebration with floats and music down a street' },
  { word: 'COASTER', category: 'Theme Parks & Fun', difficulty: 'easy',
    definition: 'A thrilling ride on a track with hills, loops, and fast turns.',
    usageExample: 'The coaster went so fast my hat nearly flew off.',
    pronunciation: 'KOH-ster',
    hint: 'A fast ride on a track with big hills and sharp turns' },
  { word: 'CAROUSEL', category: 'Theme Parks & Fun', difficulty: 'hard',
    definition: 'A spinning ride with seats shaped like horses or animals.',
    usageExample: 'My little sister loved riding the carousel horse.',
    pronunciation: 'kair-uh-SEL',
    hint: 'A spinning ride with animal-shaped seats going up and down' },
  { word: 'FIREWORKS', category: 'Theme Parks & Fun', difficulty: 'hard',
    definition: 'Colorful explosions in the night sky used to celebrate.',
    usageExample: 'The fireworks lit up the sky above the castle.',
    pronunciation: 'FYR-works',
    hint: 'Colorful explosions that light up the sky at night to celebrate' },
  { word: 'CHARACTER', category: 'Theme Parks & Fun', difficulty: 'hard',
    definition: 'A person dressed as a famous story or movie figure at a park.',
    usageExample: 'We got a photo with our favorite character at the gate.',
    pronunciation: 'KAIR-ik-ter',
    hint: 'A person dressed as your favorite movie hero at the park' },
  { word: 'SOUVENIR', category: 'Theme Parks & Fun', difficulty: 'hard',
    definition: 'A small object bought to remember a special place or trip.',
    usageExample: 'I picked a snow globe as my souvenir from the park.',
    pronunciation: 'soo-vuh-NEER',
    hint: 'A small gift you buy to remember a special place' },
  { word: 'WATERSLIDE', category: 'Theme Parks & Fun', difficulty: 'hard',
    definition: 'A long slippery slide at a water park that sends you into a pool.',
    usageExample: 'The waterslide twisted all the way to the bottom.',
    pronunciation: 'WAW-ter-slyd',
    hint: 'A slippery twisting slide that sends you into a splash pool' },
  { word: 'MONORAIL', category: 'Theme Parks & Fun', difficulty: 'hard',
    definition: 'A single-track train that glides high above the ground.',
    usageExample: 'We took the monorail to the other side of the park.',
    pronunciation: 'MON-oh-rayl',
    hint: 'A single-track train that glides high above the ground' },
  { word: 'ADMISSION', category: 'Theme Parks & Fun', difficulty: 'hard',
    definition: 'The fee you pay to enter a park or show.',
    usageExample: 'We saved up all year to pay the admission price.',
    pronunciation: 'ad-MISH-un',
    hint: 'The price you pay to get through the park gate' },
  { word: 'ATTRACTION', category: 'Theme Parks & Fun', difficulty: 'hard',
    definition: 'A popular ride, show, or activity that draws people in.',
    usageExample: 'The haunted mansion was the most popular attraction.',
    pronunciation: 'uh-TRAK-shun',
    hint: 'The most popular thing to see or do at the park' },

  // ─── WILDLIFE & SAFARI ────────────────────────────────────────────────────────
  { word: 'LION', category: 'Wildlife & Safari', difficulty: 'easy',
    definition: 'A large wild cat with a mane that is known as the king of animals.',
    usageExample: 'The lion let out a roar that echoed across the plain.',
    pronunciation: 'LY-un',
    hint: 'The big cat with a fluffy mane and a mighty roar' },
  { word: 'ZEBRA', category: 'Wildlife & Safari', difficulty: 'easy',
    definition: 'A wild horse-like animal with black and white stripes.',
    usageExample: 'A zebra stood right next to our safari truck.',
    pronunciation: 'ZEE-bruh',
    hint: 'A horse-like animal with black and white stripes' },
  { word: 'GIRAFFE', category: 'Wildlife & Safari', difficulty: 'easy',
    definition: 'The world\'s tallest animal, with a very long neck and spotted coat.',
    usageExample: 'The giraffe stretched its long neck to eat leaves from the top.',
    pronunciation: 'jih-RAF',
    hint: 'The tallest animal on Earth with a very long neck' },
  { word: 'HIPPO', category: 'Wildlife & Safari', difficulty: 'easy',
    definition: 'A very large, heavy animal that loves to rest in rivers.',
    usageExample: 'We spotted a hippo with just its eyes above the water.',
    pronunciation: 'HIP-oh',
    hint: 'A giant animal that spends most of its time in rivers' },
  { word: 'MOOSE', category: 'Wildlife & Safari', difficulty: 'easy',
    definition: 'The largest member of the deer family, with big flat antlers.',
    usageExample: 'A moose waded slowly through the shallow lake.',
    pronunciation: 'MOOS',
    hint: 'The biggest deer, with wide flat antlers' },
  { word: 'EAGLE', category: 'Wildlife & Safari', difficulty: 'easy',
    definition: 'A powerful bird of prey with sharp talons and excellent eyesight.',
    usageExample: 'The bald eagle swooped down and caught a fish.',
    pronunciation: 'EE-gul',
    hint: 'A powerful hunting bird with sharp talons and great eyesight' },
  { word: 'TIGER', category: 'Wildlife & Safari', difficulty: 'easy',
    definition: 'A large striped wild cat that is a powerful hunter.',
    usageExample: 'The tiger stalked quietly through the tall grass.',
    pronunciation: 'TY-ger',
    hint: 'A striped wild cat that is one of nature\'s best hunters' },
  { word: 'OTTER', category: 'Wildlife & Safari', difficulty: 'easy',
    definition: 'A playful furry animal that swims and loves to slide on river banks.',
    usageExample: 'The otter floated on its back while eating a clam.',
    pronunciation: 'OT-er',
    hint: 'A playful furry swimmer that floats on its back' },
  { word: 'CHEETAH', category: 'Wildlife & Safari', difficulty: 'hard',
    definition: 'The fastest land animal, covered in black spots.',
    usageExample: 'The cheetah went from zero to sixty in just three seconds.',
    pronunciation: 'CHEE-tuh',
    hint: 'The fastest land animal on Earth with black spots' },
  { word: 'ELEPHANT', category: 'Wildlife & Safari', difficulty: 'hard',
    definition: 'The largest land animal on Earth, with a long trunk and big ears.',
    usageExample: 'The elephant sprayed water on itself to cool down.',
    pronunciation: 'EL-eh-funt',
    hint: 'The biggest land animal, with a long trunk and huge ears' },
  { word: 'GORILLA', category: 'Wildlife & Safari', difficulty: 'hard',
    definition: 'The largest primate, a powerful ape that lives in forests.',
    usageExample: 'The baby gorilla held onto its mother as she walked.',
    pronunciation: 'guh-RIL-uh',
    hint: 'The largest ape, strong and gentle at the same time' },
  { word: 'CROCODILE', category: 'Wildlife & Safari', difficulty: 'hard',
    definition: 'A large reptile with thick skin and powerful jaws that lives near water.',
    usageExample: 'We kept far back from the river where the crocodile waited.',
    pronunciation: 'KROK-uh-dyl',
    hint: 'A large reptile with armored skin that waits in rivers' },
  { word: 'FLAMINGO', category: 'Wildlife & Safari', difficulty: 'hard',
    definition: 'A pink wading bird that stands on one leg.',
    usageExample: 'A hundred flamingos turned the lake bright pink.',
    pronunciation: 'fluh-MING-oh',
    hint: 'A pink bird famous for standing on just one leg' },
  { word: 'MIGRATION', category: 'Wildlife & Safari', difficulty: 'hard',
    definition: 'The seasonal journey animals make to find food or warmer weather.',
    usageExample: 'The wildebeest migration is one of the greatest shows on Earth.',
    pronunciation: 'my-GRAY-shun',
    hint: 'The long journey animals take with the changing seasons' },
  { word: 'PREDATOR', category: 'Wildlife & Safari', difficulty: 'hard',
    definition: 'An animal that hunts and eats other animals.',
    usageExample: 'The cheetah is a fast and clever predator.',
    pronunciation: 'PRED-uh-ter',
    hint: 'An animal that hunts other animals for food' },
  { word: 'MANATEE', category: 'Wildlife & Safari', difficulty: 'hard',
    definition: 'A gentle, slow-moving sea mammal sometimes called a sea cow.',
    usageExample: 'We watched a manatee float past the dock.',
    pronunciation: 'MAN-uh-tee',
    hint: 'A gentle sea mammal sometimes called a sea cow' },

  // ─── BIG CITY ─────────────────────────────────────────────────────────────────
  { word: 'TAXI', category: 'Big City', difficulty: 'easy',
    definition: 'A car you pay to drive you anywhere in the city.',
    usageExample: 'We hailed a yellow taxi to get to the museum.',
    pronunciation: 'TAK-see',
    hint: 'A car you pay to take you anywhere in the city' },
  { word: 'SUBWAY', category: 'Big City', difficulty: 'easy',
    definition: 'An underground train that carries people around a city.',
    usageExample: 'We took the subway to avoid the traffic.',
    pronunciation: 'SUB-way',
    hint: 'An underground train that travels under city streets' },
  { word: 'TOWER', category: 'Big City', difficulty: 'easy',
    definition: 'A very tall, narrow building that stands above the rest.',
    usageExample: 'We could see the whole city from the top of the tower.',
    pronunciation: 'TOW-er',
    hint: 'The tallest building you can see for miles around the city' },
  { word: 'MARKET', category: 'Big City', difficulty: 'easy',
    definition: 'An outdoor or covered place where people buy and sell things.',
    usageExample: 'The market was full of fresh fruit and colorful crafts.',
    pronunciation: 'MAR-ket',
    hint: 'An outdoor place where vendors sell food and crafts' },
  { word: 'PARK', category: 'Big City', difficulty: 'easy',
    definition: 'A green outdoor space in a city for walking, playing, and relaxing.',
    usageExample: 'We ate lunch on the grass in the middle of the city park.',
    pronunciation: 'PARK',
    hint: 'A green space in the city for picnics and play' },
  { word: 'PLAZA', category: 'Big City', difficulty: 'easy',
    definition: 'An open paved area in a city where people gather.',
    usageExample: 'We sat in the plaza and watched the pigeons.',
    pronunciation: 'PLAH-zuh',
    hint: 'An open paved square where city people gather' },
  { word: 'CAFE', category: 'Big City', difficulty: 'easy',
    definition: 'A small restaurant where you can get drinks and light food.',
    usageExample: 'We stopped at a sidewalk cafe for hot chocolate.',
    pronunciation: 'kuh-FAY',
    hint: 'A small place to get a drink and a snack' },
  { word: 'FERRY', category: 'Big City', difficulty: 'easy',
    definition: 'A boat that carries people and cars across a body of water.',
    usageExample: 'We took the ferry to see the skyline from the water.',
    pronunciation: 'FAIR-ee',
    hint: 'A boat that crosses a river or bay in a city' },
  { word: 'SKYSCRAPER', category: 'Big City', difficulty: 'hard',
    definition: 'A building so tall it seems to touch the sky.',
    usageExample: 'The skyscraper had over a hundred floors.',
    pronunciation: 'SKY-skray-per',
    hint: 'A building so tall it seems to touch the clouds' },
  { word: 'BOULEVARD', category: 'Big City', difficulty: 'hard',
    definition: 'A wide city road lined with trees on both sides.',
    usageExample: 'We strolled along the boulevard past the restaurants.',
    pronunciation: 'BULL-uh-vard',
    hint: 'A wide city road lined with trees on both sides' },
  { word: 'DOWNTOWN', category: 'Big City', difficulty: 'hard',
    definition: 'The central business area of a city with tall buildings.',
    usageExample: 'The tallest skyscrapers are all in downtown.',
    pronunciation: 'DOWN-town',
    hint: 'The center of a city where the tallest buildings stand' },
  { word: 'CROSSWALK', category: 'Big City', difficulty: 'hard',
    definition: 'A marked path across a road where pedestrians can safely cross.',
    usageExample: 'We waited at the crosswalk until the light turned green.',
    pronunciation: 'KROSS-wok',
    hint: 'Painted stripes on a road where it is safe to walk across' },
  { word: 'SIDEWALK', category: 'Big City', difficulty: 'hard',
    definition: 'A paved path along the side of a road for people to walk on.',
    usageExample: 'The sidewalk was packed with people heading to the show.',
    pronunciation: 'SYD-wok',
    hint: 'The paved path for people walking beside the road' },
  { word: 'INTERSECTION', category: 'Big City', difficulty: 'hard',
    definition: 'The place where two or more roads meet and cross each other.',
    usageExample: 'There were traffic lights at every intersection downtown.',
    pronunciation: 'in-ter-SEK-shun',
    hint: 'The spot where two streets cross each other' },
  { word: 'ARCHITECTURE', category: 'Big City', difficulty: 'hard',
    definition: 'The design and style of buildings.',
    usageExample: 'We admired the beautiful architecture of the old cathedral.',
    pronunciation: 'AR-kih-tek-cher',
    hint: 'The art and science of designing buildings' },
  { word: 'NEIGHBORHOOD', category: 'Big City', difficulty: 'hard',
    definition: 'A small area of a city where people live and know each other.',
    usageExample: 'Each neighborhood had its own cafes and small shops.',
    pronunciation: 'NAY-ber-hood',
    hint: 'A small community of streets within a bigger city' },

  // ─── ROAD TRIP ────────────────────────────────────────────────────────────────
  { word: 'MAP', category: 'Road Trip', difficulty: 'easy',
    definition: 'A drawing that shows roads, cities, and how to get from place to place.',
    usageExample: 'Dad spread out the map on the hood of the car.',
    pronunciation: 'MAP',
    hint: 'A drawing that shows roads and how to get places' },
  { word: 'SIGN', category: 'Road Trip', difficulty: 'easy',
    definition: 'A board on the road that gives directions or warnings.',
    usageExample: 'The sign pointed left toward the national park entrance.',
    pronunciation: 'SYN',
    hint: 'A board beside the road that gives you directions' },
  { word: 'LANE', category: 'Road Trip', difficulty: 'easy',
    definition: 'One of the strips on a road that cars drive in.',
    usageExample: 'We moved to the left lane to pass the slow truck.',
    pronunciation: 'LAYN',
    hint: 'One of the marked strips on a road for cars' },
  { word: 'EXIT', category: 'Road Trip', difficulty: 'easy',
    definition: 'A ramp that takes you off a highway toward a city or town.',
    usageExample: 'Our exit was only two miles away.',
    pronunciation: 'EK-sit',
    hint: 'A ramp that leads you off the highway' },
  { word: 'TOLL', category: 'Road Trip', difficulty: 'easy',
    definition: 'A small fee you pay to drive on certain roads or bridges.',
    usageExample: 'We stopped at the toll booth and paid before crossing.',
    pronunciation: 'TOHL',
    hint: 'A small fee you pay to use certain roads or bridges' },
  { word: 'DETOUR', category: 'Road Trip', difficulty: 'easy',
    definition: 'An alternate route you take when the main road is blocked.',
    usageExample: 'The detour added twenty minutes to our trip.',
    pronunciation: 'DEE-toor',
    hint: 'An alternate route when the main road is blocked' },
  { word: 'REST', category: 'Road Trip', difficulty: 'easy',
    definition: 'A break from driving to stretch your legs and use the bathroom.',
    usageExample: 'We pulled off at a rest stop so everyone could get out.',
    pronunciation: 'REST',
    hint: 'A break stop so everyone can stretch and recharge' },
  { word: 'COMPASS', category: 'Road Trip', difficulty: 'easy',
    definition: 'A tool that always points north to help you find your direction.',
    usageExample: 'We used the compass to figure out which way was north.',
    pronunciation: 'KUM-pus',
    hint: 'A tool with a needle that always points north' },
  { word: 'HIGHWAY', category: 'Road Trip', difficulty: 'hard',
    definition: 'A wide, fast road built for traveling long distances.',
    usageExample: 'We drove on the highway for three hours straight.',
    pronunciation: 'HY-way',
    hint: 'A wide fast road built for long-distance travel' },
  { word: 'OVERPASS', category: 'Road Trip', difficulty: 'hard',
    definition: 'A bridge that carries one road over the top of another.',
    usageExample: 'We went under the overpass and then took our exit.',
    pronunciation: 'OH-ver-pas',
    hint: 'A bridge that carries one road over the top of another' },
  { word: 'FREEWAY', category: 'Road Trip', difficulty: 'hard',
    definition: 'A fast divided highway with no traffic lights or stops.',
    usageExample: 'The freeway took us straight into the heart of the city.',
    pronunciation: 'FREE-way',
    hint: 'A fast highway with no traffic lights or stops' },
  { word: 'JUNCTION', category: 'Road Trip', difficulty: 'hard',
    definition: 'A place where two or more roads or routes come together.',
    usageExample: 'Turn left at the junction and then follow the signs.',
    pronunciation: 'JUNK-shun',
    hint: 'The spot where two or more roads come together' },
  { word: 'MILEAGE', category: 'Road Trip', difficulty: 'hard',
    definition: 'The number of miles a car has traveled.',
    usageExample: 'We checked the mileage to see how far we had come.',
    pronunciation: 'MY-lij',
    hint: 'Something you track on a long road trip' },
  { word: 'CARPOOL', category: 'Road Trip', difficulty: 'hard',
    definition: 'When a group of people share one car for the same journey.',
    usageExample: 'Our neighbors joined the carpool to the game.',
    pronunciation: 'KAR-pool',
    hint: 'When a group of people share one car for the same journey' },
  { word: 'ITINERARY', category: 'Road Trip', difficulty: 'hard',
    definition: 'A plan showing all the places you will visit on a trip and when.',
    usageExample: 'Mom printed the itinerary so we knew every stop.',
    pronunciation: 'eye-TIN-er-air-ee',
    hint: 'A printed plan of all your stops and times on a trip' },
  { word: 'WINDSHIELD', category: 'Road Trip', difficulty: 'hard',
    definition: 'The large glass window at the front of a car.',
    usageExample: 'Rain splattered all over the windshield on the mountain road.',
    pronunciation: 'WIND-sheeld',
    hint: 'The big glass window at the very front of a car' },

  // ─── GEOGRAPHY — WORLD ────────────────────────────────────────────────────────
  { word: 'GLOBE', category: 'Geography \u2014 World', difficulty: 'easy',
    definition: 'A round model of the Earth showing all the countries and oceans.',
    usageExample: 'We spun the globe and landed on a country in Africa.',
    pronunciation: 'GLOHB',
    hint: 'A round ball-shaped model of the whole Earth' },
  { word: 'RIVER', category: 'Geography \u2014 World', difficulty: 'easy',
    definition: 'A large natural flow of water that moves toward the sea.',
    usageExample: 'The river wound through the green valley.',
    pronunciation: 'RIV-er',
    hint: 'A long natural stream of water flowing toward the sea' },
  { word: 'LAKE', category: 'Geography \u2014 World', difficulty: 'easy',
    definition: 'A large body of still water surrounded by land.',
    usageExample: 'We rented a canoe and paddled across the calm lake.',
    pronunciation: 'LAYK',
    hint: 'A large body of still water surrounded by land' },
  { word: 'ISLAND', category: 'Geography \u2014 World', difficulty: 'easy',
    definition: 'A piece of land completely surrounded by water.',
    usageExample: 'We took a ferry to reach the small island.',
    pronunciation: 'EYE-lund',
    hint: 'Land with water on every side' },
  { word: 'CAPE', category: 'Geography \u2014 World', difficulty: 'easy',
    definition: 'A pointed piece of land that sticks out into the sea.',
    usageExample: 'We watched the sunset from the tip of the cape.',
    pronunciation: 'KAYP',
    hint: 'A pointed piece of land sticking out into the sea' },
  { word: 'GULF', category: 'Geography \u2014 World', difficulty: 'easy',
    definition: 'A large area of sea partly surrounded by land.',
    usageExample: 'Ships sailed slowly through the warm gulf waters.',
    pronunciation: 'GULF',
    hint: 'A large bay where the sea is partly surrounded by land' },
  { word: 'DELTA', category: 'Geography \u2014 World', difficulty: 'easy',
    definition: 'A flat triangle of land where a river fans out and meets the sea.',
    usageExample: 'The river delta was full of birds and wildlife.',
    pronunciation: 'DEL-tuh',
    hint: 'Where a river spreads out and meets the ocean' },
  { word: 'ATLAS', category: 'Geography \u2014 World', difficulty: 'easy',
    definition: 'A book of maps showing the whole world.',
    usageExample: 'We looked up our destination in the atlas.',
    pronunciation: 'AT-lus',
    hint: 'A book full of maps of the whole world' },
  { word: 'CONTINENT', category: 'Geography \u2014 World', difficulty: 'hard',
    definition: 'One of the seven huge landmasses that make up the Earth.',
    usageExample: 'Africa is the second largest continent on Earth.',
    pronunciation: 'KON-tih-nent',
    hint: 'One of the seven giant landmasses on Earth' },
  { word: 'PENINSULA', category: 'Geography \u2014 World', difficulty: 'hard',
    definition: 'A long piece of land surrounded by water on three sides.',
    usageExample: 'Florida is a peninsula with ocean on both sides.',
    pronunciation: 'peh-NIN-syoo-luh',
    hint: 'Land with water on three of its four sides' },
  { word: 'EQUATOR', category: 'Geography \u2014 World', difficulty: 'hard',
    definition: 'An imaginary line around the middle of the Earth.',
    usageExample: 'Countries near the equator are usually very hot.',
    pronunciation: 'ee-KWAY-ter',
    hint: 'An imaginary line that circles the middle of the Earth' },
  { word: 'HEMISPHERE', category: 'Geography \u2014 World', difficulty: 'hard',
    definition: 'Half of the Earth, either the northern or southern half.',
    usageExample: 'Australia is in the southern hemisphere.',
    pronunciation: 'HEM-ih-sfeer',
    hint: 'Half of the Earth, either the top half or the bottom half' },
  { word: 'LONGITUDE', category: 'Geography \u2014 World', difficulty: 'hard',
    definition: 'Lines on a map that run north to south and measure east-west position.',
    usageExample: 'The ship\'s captain knew the exact longitude to navigate home.',
    pronunciation: 'LON-jih-tood',
    hint: 'Lines on a map that measure how far east or west you are' },
  { word: 'LATITUDE', category: 'Geography \u2014 World', difficulty: 'hard',
    definition: 'Lines on a map that run east to west and measure north-south position.',
    usageExample: 'The two cities were at the same latitude but on opposite coasts.',
    pronunciation: 'LAT-ih-tood',
    hint: 'Lines on a map that measure how far north or south you are' },
  { word: 'ARCHIPELAGO', category: 'Geography \u2014 World', difficulty: 'hard',
    definition: 'A group or chain of islands in the ocean.',
    usageExample: 'Hawaii is an archipelago in the Pacific Ocean.',
    pronunciation: 'ar-kih-PEL-uh-goh',
    hint: 'A group or chain of islands scattered across the ocean' },
  { word: 'TUNDRA', category: 'Geography \u2014 World', difficulty: 'hard',
    definition: 'A flat, treeless, very cold landscape found near the North Pole.',
    usageExample: 'The tundra was frozen for most of the year.',
    pronunciation: 'TUN-druh',
    hint: 'A freezing flat landscape near the North Pole' },
];

export function getCategoriesForTrip(
  cityGroup: string,
  stopTypes: string[],
  interests: string[]
): string[] {
  const city = cityGroup.toLowerCase();
  const categories: string[] = [];

  categories.push('Geography \u2014 Destination');

  const beachCities = ['miami', 'honolulu', 'san diego', 'santa monica',
    'virginia beach', 'myrtle beach', 'newport'];
  const mountainCities = ['denver', 'jackson hole', 'yellowstone',
    'asheville', 'salt lake city', 'big island'];
  const desertCities = ['las vegas', 'phoenix', 'santa fe',
    'sedona', 'tucson', 'albuquerque'];
  const historyCities = ['washington dc', 'philadelphia', 'boston',
    'savannah', 'charleston', 'gettysburg'];
  const themeParkCities = ['orlando', 'anaheim', 'san antonio'];

  if (beachCities.some(c => city.includes(c)))
    categories.push('Beach & Ocean');
  if (mountainCities.some(c => city.includes(c)))
    categories.push('Mountains & Nature');
  if (desertCities.some(c => city.includes(c)))
    categories.push('Desert & Southwest');
  if (historyCities.some(c => city.includes(c)))
    categories.push('History & Landmarks');
  if (themeParkCities.some(c => city.includes(c)))
    categories.push('Theme Parks & Fun');
  if (stopTypes.includes('wildlife') || interests.includes('animals'))
    categories.push('Wildlife & Safari');

  if (categories.length < 3) {
    categories.push('Big City');
    categories.push('Road Trip');
  }

  categories.push('Geography \u2014 World');
  return [...new Set(categories)];
}

function toAlphaOnly(s: string): string {
  return s.toUpperCase().replace(/[^A-Z]/g, '');
}

export function getDestinationWords(trip: {
  city?: string;
  state?: string;
  stops?: { name?: string }[];
}): HangmanWord[] {
  const words: HangmanWord[] = [];
  const city = trip.city ? toAlphaOnly(trip.city) : undefined;
  const state = trip.state ? toAlphaOnly(trip.state) : undefined;

  if (city && city.length >= 3 && city.length <= 12) {
    words.push({
      word: city,
      category: 'Geography \u2014 Destination',
      difficulty: city.length > 6 ? 'hard' : 'easy',
      definition: 'The city you are visiting on this trip!',
      usageExample: `We are going to ${trip.city} for our family vacation.`,
      pronunciation: (trip.city ?? '').toUpperCase(),
      hint: 'This is the city you are visiting on your trip',
    });
  }

  if (state && state !== city && state.length >= 3 && state.length <= 12) {
    words.push({
      word: state,
      category: 'Geography \u2014 Destination',
      difficulty: state.length > 6 ? 'hard' : 'easy',
      definition: `The state where ${trip.city} is located.`,
      usageExample: `${trip.city} is in the state of ${trip.state}.`,
      pronunciation: (trip.state ?? '').toUpperCase(),
      hint: `This is the state where ${trip.city ?? 'your destination'} is located`,
    });
  }

  const stops = trip.stops?.slice(0, 3) ?? [];
  stops.forEach((stop) => {
    const w = stop.name ? toAlphaOnly(stop.name) : undefined;
    if (w && w.length >= 4 && w.length <= 12) {
      words.push({
        word: w,
        category: 'Geography \u2014 Destination',
        difficulty: w.length > 6 ? 'hard' : 'easy',
        definition: 'A place you will visit on this trip!',
        usageExample: `We are going to ${stop.name} today.`,
        pronunciation: (stop.name ?? '').toUpperCase(),
        hint: 'This is one of the places you will visit on your trip',
      });
    }
  });

  return words;
}
