export const CROSSWORLD_DATA = [
  { country: "United States", capital: "Washington", hint: "Home of the White House and cherry blossoms" },
  { country: "Canada", capital: "Ottawa", hint: "Famous for its tulip festival and Rideau Canal skating" },
  { country: "Mexico", capital: "MexicoCity", hint: "Built on ancient Aztec ruins with sinking buildings" },
  { country: "Brazil", capital: "Brasilia", hint: "Shaped like an airplane when viewed from above" },
  { country: "Argentina", capital: "BuenosAires", hint: "Birthplace of Tango dance" },
  { country: "Chile", capital: "Santiago", hint: "Surrounded by the Andes Mountains" },
  { country: "Peru", capital: "Lima", hint: "Famous for ceviche and Pacific Ocean views" },
  { country: "Colombia", capital: "Bogota", hint: "One of the highest capitals in the world" },
  { country: "Venezuela", capital: "Caracas", hint: "Near the world's highest waterfall" },
  { country: "United Kingdom", capital: "London", hint: "Home of Big Ben and the Royal Guards" },
  { country: "France", capital: "Paris", hint: "City of Love with the Eiffel Tower" },
  { country: "Germany", capital: "Berlin", hint: "Famous wall once divided this city" },
  { country: "Italy", capital: "Rome", hint: "Ancient Colosseum and Gladiators lived here" },
  { country: "Spain", capital: "Madrid", hint: "Home to the Royal Palace and flamenco" },
  { country: "Portugal", capital: "Lisbon", hint: "Famous for colorful trams on steep hills" },
  { country: "Netherlands", capital: "Amsterdam", hint: "City of bikes, canals and tulips" },
  { country: "Belgium", capital: "Brussels", hint: "Famous for chocolate and waffles" },
  { country: "Switzerland", capital: "Bern", hint: "Home to famous clock tower and bears" },
  { country: "Austria", capital: "Vienna", hint: "City of Mozart and classical music" },
  { country: "Sweden", capital: "Stockholm", hint: "Built on 14 islands with Nobel Prize ceremony" },
  { country: "Norway", capital: "Oslo", hint: "Land of Vikings and Northern Lights" },
  { country: "Denmark", capital: "Copenhagen", hint: "Home to the Little Mermaid statue" },
  { country: "Finland", capital: "Helsinki", hint: "Santa Claus' neighboring city of saunas" },
  { country: "Ireland", capital: "Dublin", hint: "Land of leprechauns and four-leaf clovers" },
  { country: "Russia", capital: "Moscow", hint: "Famous Red Square and colorful onion domes" },
  { country: "China", capital: "Beijing", hint: "Home of the Forbidden City and pandas nearby" },
  { country: "Japan", capital: "Tokyo", hint: "City of sushi, anime and cherry blossoms" },
  { country: "South Korea", capital: "Seoul", hint: "K-pop music started here with ancient palaces" },
  { country: "India", capital: "Delhi", hint: "Near the Taj Mahal with sacred cows" },
  { country: "Pakistan", capital: "Islamabad", hint: "One of the world's newest planned capitals" },
  { country: "Bangladesh", capital: "Dhaka", hint: "Known as the City of Mosques" },
  { country: "Sri Lanka", capital: "Colombo", hint: "Island nation famous for tea and elephants" },
  { country: "Nepal", capital: "Kathmandu", hint: "Gateway to Mount Everest climbing" },
  { country: "Thailand", capital: "Bangkok", hint: "City of golden temples and elephants" },
  { country: "Vietnam", capital: "Hanoi", hint: "Famous for street food and water puppets" },
  { country: "Philippines", capital: "Manila", hint: "Known for jeepneys and beautiful beaches nearby" },
  { country: "Indonesia", capital: "Jakarta", hint: "Home to Komodo dragons nearby" },
  { country: "Malaysia", capital: "KualaLumpur", hint: "Has the famous Petronas Twin Towers" },
  { country: "Singapore", capital: "Singapore", hint: "City-state with Marina Bay Sands rooftop pool" },
  { country: "Australia", capital: "Canberra", hint: "Planned city with lots of kangaroos nearby" },
  { country: "New Zealand", capital: "Wellington", hint: "Where The Lord of the Rings was made" },
  { country: "South Africa", capital: "Pretoria", hint: "Known as the Jacaranda City for purple trees" },
  { country: "Egypt", capital: "Cairo", hint: "Next to the ancient Pyramids and Sphinx" },
  { country: "Morocco", capital: "Rabat", hint: "Ancient city with blue doors and colorful markets" },
  { country: "Kenya", capital: "Nairobi", hint: "Famous for safari lions and wildlife" },
  { country: "Nigeria", capital: "Abuja", hint: "Shaped like an eagle from above" },
  { country: "Ghana", capital: "Accra", hint: "Known for colorful kente cloth and drums" },
  { country: "Ethiopia", capital: "AddisAbaba", hint: "Birthplace of coffee beans" },
  { country: "Tanzania", capital: "Dodoma", hint: "Near Mount Kilimanjaro and zebras" },
  { country: "Uganda", capital: "Kampala", hint: "Home to mountain gorillas nearby" },
  { country: "Saudi Arabia", capital: "Riyadh", hint: "Desert city with camel markets" },
  { country: "United Arab Emirates", capital: "AbuDhabi", hint: "Has the world's fastest roller coaster" },
  { country: "Qatar", capital: "Doha", hint: "Hosted FIFA World Cup 2022" },
  { country: "Kuwait", capital: "KuwaitCity", hint: "Famous Kuwait Towers look like water rockets" },
  { country: "Israel", capital: "Jerusalem", hint: "Ancient holy city with the Western Wall" },
  { country: "Turkey", capital: "Ankara", hint: "Home to angora cats and fluffy goats" },
  { country: "Iran", capital: "Tehran", hint: "Near snowy mountains with ancient bazaars" },
  { country: "Iraq", capital: "Baghdad", hint: "Ancient city from 1001 Arabian Nights stories" },
  { country: "Greece", capital: "Athens", hint: "Where the Olympic Games were born" },
  { country: "Poland", capital: "Warsaw", hint: "Famous composer Chopin was born here" },
  { country: "Czech Republic", capital: "Prague", hint: "City of fairy tale castles and bridges" },
  { country: "Hungary", capital: "Budapest", hint: "Famous for hot spring baths and paprika" },
  { country: "Romania", capital: "Bucharest", hint: "Near Dracula's castle in Transylvania" },
  { country: "Ukraine", capital: "Kyiv", hint: "Famous for golden-domed churches" },
  { country: "Cuba", capital: "Havana", hint: "City of colorful old cars and salsa music" },
  { country: "Jamaica", capital: "Kingston", hint: "Birthplace of reggae music and Bob Marley" },
  { country: "North Korea", capital: "Pyongyang", hint: "Most secretive city in the world" },
  { country: "Myanmar", capital: "Naypyidaw", hint: "One of the newest capitals with wide empty roads" },
  { country: "Taiwan", capital: "Taipei", hint: "Famous night markets and bubble tea" }
];

// Filter to ensure they fit in grid (length <= 8)
export const FILTERED_CROSSWORLD_DATA = CROSSWORLD_DATA.filter(item => item.capital.length <= 8);
