export const CONTINENTS = [
  { id: "africa", name: "Africa", emoji: "🦁" },
  { id: "asia", name: "Asia", emoji: "🐼" },
  { id: "europe", name: "Europe", emoji: "🏰" },
  { id: "north_america", name: "North America", emoji: "🗽" },
  { id: "south_america", name: "South America", emoji: "🦜" },
  { id: "oceania", name: "Oceania", emoji: "🦘" },
] as const;

export type ContinentId = typeof CONTINENTS[number]["id"];

export const COUNTRIES_BY_CONTINENT: Record<ContinentId, { code: string; name: string; flag: string }[]> = {
  africa: [
    { code: "ZA", name: "South Africa", flag: "🇿🇦" },
    { code: "EG", name: "Egypt", flag: "🇪🇬" },
    { code: "KE", name: "Kenya", flag: "🇰🇪" },
    { code: "MA", name: "Morocco", flag: "🇲🇦" },
    { code: "TZ", name: "Tanzania", flag: "🇹🇿" },
    { code: "NG", name: "Nigeria", flag: "🇳🇬" },
    { code: "ET", name: "Ethiopia", flag: "🇪🇹" },
    { code: "GH", name: "Ghana", flag: "🇬🇭" },
  ],
  asia: [
    { code: "JP", name: "Japan", flag: "🇯🇵" },
    { code: "CN", name: "China", flag: "🇨🇳" },
    { code: "IN", name: "India", flag: "🇮🇳" },
    { code: "TH", name: "Thailand", flag: "🇹🇭" },
    { code: "VN", name: "Vietnam", flag: "🇻🇳" },
    { code: "KR", name: "South Korea", flag: "🇰🇷" },
    { code: "SG", name: "Singapore", flag: "🇸🇬" },
    { code: "MY", name: "Malaysia", flag: "🇲🇾" },
    { code: "ID", name: "Indonesia", flag: "🇮🇩" },
    { code: "PH", name: "Philippines", flag: "🇵🇭" },
    { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
    { code: "IL", name: "Israel", flag: "🇮🇱" },
    { code: "TR", name: "Turkey", flag: "🇹🇷" },
  ],
  europe: [
    { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
    { code: "FR", name: "France", flag: "🇫🇷" },
    { code: "DE", name: "Germany", flag: "🇩🇪" },
    { code: "IT", name: "Italy", flag: "🇮🇹" },
    { code: "ES", name: "Spain", flag: "🇪🇸" },
    { code: "NL", name: "Netherlands", flag: "🇳🇱" },
    { code: "PT", name: "Portugal", flag: "🇵🇹" },
    { code: "GR", name: "Greece", flag: "🇬🇷" },
    { code: "CH", name: "Switzerland", flag: "🇨🇭" },
    { code: "AT", name: "Austria", flag: "🇦🇹" },
    { code: "SE", name: "Sweden", flag: "🇸🇪" },
    { code: "NO", name: "Norway", flag: "🇳🇴" },
    { code: "DK", name: "Denmark", flag: "🇩🇰" },
    { code: "IE", name: "Ireland", flag: "🇮🇪" },
    { code: "PL", name: "Poland", flag: "🇵🇱" },
    { code: "CZ", name: "Czech Republic", flag: "🇨🇿" },
    { code: "BE", name: "Belgium", flag: "🇧🇪" },
    { code: "FI", name: "Finland", flag: "🇫🇮" },
  ],
  north_america: [
    { code: "US", name: "United States", flag: "🇺🇸" },
    { code: "CA", name: "Canada", flag: "🇨🇦" },
    { code: "MX", name: "Mexico", flag: "🇲🇽" },
    { code: "CR", name: "Costa Rica", flag: "🇨🇷" },
    { code: "PA", name: "Panama", flag: "🇵🇦" },
    { code: "JM", name: "Jamaica", flag: "🇯🇲" },
    { code: "BS", name: "Bahamas", flag: "🇧🇸" },
    { code: "DO", name: "Dominican Republic", flag: "🇩🇴" },
    { code: "CU", name: "Cuba", flag: "🇨🇺" },
    { code: "PR", name: "Puerto Rico", flag: "🇵🇷" },
  ],
  south_america: [
    { code: "BR", name: "Brazil", flag: "🇧🇷" },
    { code: "AR", name: "Argentina", flag: "🇦🇷" },
    { code: "CL", name: "Chile", flag: "🇨🇱" },
    { code: "PE", name: "Peru", flag: "🇵🇪" },
    { code: "CO", name: "Colombia", flag: "🇨🇴" },
    { code: "EC", name: "Ecuador", flag: "🇪🇨" },
    { code: "VE", name: "Venezuela", flag: "🇻🇪" },
    { code: "UY", name: "Uruguay", flag: "🇺🇾" },
    { code: "BO", name: "Bolivia", flag: "🇧🇴" },
  ],
  oceania: [
    { code: "AU", name: "Australia", flag: "🇦🇺" },
    { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
    { code: "FJ", name: "Fiji", flag: "🇫🇯" },
    { code: "PG", name: "Papua New Guinea", flag: "🇵🇬" },
    { code: "WS", name: "Samoa", flag: "🇼🇸" },
    { code: "TO", name: "Tonga", flag: "🇹🇴" },
    { code: "VU", name: "Vanuatu", flag: "🇻🇺" },
  ],
};

export const MONTHS = [
  { value: 1, label: "January" },
  { value: 2, label: "February" },
  { value: 3, label: "March" },
  { value: 4, label: "April" },
  { value: 5, label: "May" },
  { value: 6, label: "June" },
  { value: 7, label: "July" },
  { value: 8, label: "August" },
  { value: 9, label: "September" },
  { value: 10, label: "October" },
  { value: 11, label: "November" },
  { value: 12, label: "December" },
] as const;

export const YEARS = Array.from({ length: 10 }, (_, i) => {
  const year = new Date().getFullYear() + i;
  return { value: year, label: String(year) };
});

export interface TripTraveler {
  explorerId?: string;
  name: string;
  avatarKey?: string;
  isParent?: boolean;
  age?: string;
}

export const KNOWN_STOP_SUGGESTIONS: Record<string, { name: string; stopType: string; displayOrder: number; address?: string }[]> = {
  "chicago": [
    { name: "Millennium Park & Cloud Gate", stopType: "landmark", displayOrder: 1, address: "201 E Randolph St, Chicago, IL 60602" },
    { name: "Navy Pier", stopType: "landmark", displayOrder: 2, address: "600 E Grand Ave, Chicago, IL 60611" },
    { name: "Shedd Aquarium", stopType: "museum", displayOrder: 3, address: "1200 S DuSable Lake Shore Dr, Chicago, IL 60605" },
    { name: "Field Museum", stopType: "museum", displayOrder: 4, address: "1400 S DuSable Lake Shore Dr, Chicago, IL 60605" },
    { name: "Art Institute of Chicago", stopType: "museum", displayOrder: 5, address: "111 S Michigan Ave, Chicago, IL 60603" },
    { name: "Willis Tower Skydeck", stopType: "landmark", displayOrder: 6, address: "233 S Wacker Dr, Chicago, IL 60606" },
    { name: "Lincoln Park Zoo", stopType: "nature", displayOrder: 7, address: "2001 N Clark St, Chicago, IL 60614" },
    { name: "Chicago Riverwalk", stopType: "nature", displayOrder: 8, address: "E Riverwalk, Chicago, IL 60601" },
    { name: "Museum of Science and Industry", stopType: "museum", displayOrder: 9, address: "5700 S DuSable Lake Shore Dr, Chicago, IL 60637" },
    { name: "Magnificent Mile", stopType: "city", displayOrder: 10, address: "N Michigan Ave, Chicago, IL 60611" },
  ],
  "big island": [
    { name: "Volcanoes National Park", stopType: "nature", displayOrder: 1, address: "1 Crater Rim Dr, Hawaii Volcanoes National Park, HI 96718" },
    { name: "Mauna Kea Summit", stopType: "nature", displayOrder: 2, address: "Mauna Kea Access Rd, Hilo, HI 96720" },
    { name: "Akaka Falls", stopType: "nature", displayOrder: 3, address: "875 Akaka Falls Rd, Honomu, HI 96728" },
    { name: "Punalu'u Black Sand Beach", stopType: "beach", displayOrder: 4, address: "96-876 Government Rd, Pahala, HI 96777" },
    { name: "Kona Town", stopType: "city", displayOrder: 5, address: "Alii Dr, Kailua-Kona, HI 96740" },
    { name: "Waipio Valley", stopType: "nature", displayOrder: 6, address: "Waipio Valley Rd, Honokaa, HI 96727" },
    { name: "Kealakekua Bay", stopType: "beach", displayOrder: 7, address: "82-6099 Puuhonua Rd, Captain Cook, HI 96704" },
    { name: "Hilo Farmers Market", stopType: "landmark", displayOrder: 8, address: "25 Mamo St, Hilo, HI 96720" },
    { name: "Rainbow Falls", stopType: "nature", displayOrder: 9, address: "40 Waianuenue Ave, Hilo, HI 96720" },
    { name: "Hapuna Beach", stopType: "beach", displayOrder: 10, address: "Old Puako Rd, Waimea, HI 96743" },
  ],
  "maui": [
    { name: "Haleakala National Park", stopType: "nature", displayOrder: 1, address: "Haleakala Hwy, Kula, HI 96790" },
    { name: "Road to Hana", stopType: "nature", displayOrder: 2, address: "Hana Hwy, Maui, HI 96713" },
    { name: "Lahaina Town", stopType: "city", displayOrder: 3, address: "Front St, Lahaina, HI 96761" },
    { name: "Molokini Crater", stopType: "beach", displayOrder: 4, address: "Molokini Crater, Maui, HI" },
    { name: "Iao Valley", stopType: "nature", displayOrder: 5, address: "54 S High St, Wailuku, HI 96793" },
  ],
  "oahu": [
    { name: "Waikiki Beach", stopType: "beach", displayOrder: 1, address: "Kalakaua Ave, Honolulu, HI 96815" },
    { name: "Pearl Harbor", stopType: "landmark", displayOrder: 2, address: "1 Arizona Memorial Pl, Honolulu, HI 96818" },
    { name: "Diamond Head", stopType: "nature", displayOrder: 3, address: "Diamond Head Rd, Honolulu, HI 96816" },
    { name: "North Shore", stopType: "beach", displayOrder: 4, address: "59-104 Kamehameha Hwy, Haleiwa, HI 96712" },
    { name: "Honolulu", stopType: "city", displayOrder: 5, address: "Honolulu, HI 96813" },
  ],
};

export function getSuggestedStops(cityName: string): { name: string; stopType: string; displayOrder: number; address?: string }[] | null {
  const normalized = cityName.toLowerCase().trim();
  return KNOWN_STOP_SUGGESTIONS[normalized] || null;
}

export interface PopularCity {
  name: string;
  country: string;
  countryCode: string;
  continentId: ContinentId;
}

export const POPULAR_CITIES: PopularCity[] = [
  { name: "Paris", country: "France", countryCode: "FR", continentId: "europe" },
  { name: "London", country: "United Kingdom", countryCode: "GB", continentId: "europe" },
  { name: "Tokyo", country: "Japan", countryCode: "JP", continentId: "asia" },
  { name: "Rome", country: "Italy", countryCode: "IT", continentId: "europe" },
  { name: "New York", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Sydney", country: "Australia", countryCode: "AU", continentId: "oceania" },
  { name: "Barcelona", country: "Spain", countryCode: "ES", continentId: "europe" },
  { name: "Dubai", country: "United Arab Emirates", countryCode: "AE", continentId: "asia" },
  { name: "Cairo", country: "Egypt", countryCode: "EG", continentId: "africa" },
  { name: "Rio de Janeiro", country: "Brazil", countryCode: "BR", continentId: "south_america" },
  { name: "Bangkok", country: "Thailand", countryCode: "TH", continentId: "asia" },
  { name: "Istanbul", country: "Turkey", countryCode: "TR", continentId: "asia" },
  { name: "Amsterdam", country: "Netherlands", countryCode: "NL", continentId: "europe" },
  { name: "Berlin", country: "Germany", countryCode: "DE", continentId: "europe" },
  { name: "Lisbon", country: "Portugal", countryCode: "PT", continentId: "europe" },
  { name: "Singapore", country: "Singapore", countryCode: "SG", continentId: "asia" },
  { name: "Seoul", country: "South Korea", countryCode: "KR", continentId: "asia" },
  { name: "Delhi", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Nairobi", country: "Kenya", countryCode: "KE", continentId: "africa" },
  { name: "Buenos Aires", country: "Argentina", countryCode: "AR", continentId: "south_america" },
  { name: "Lima", country: "Peru", countryCode: "PE", continentId: "south_america" },
  { name: "Mexico City", country: "Mexico", countryCode: "MX", continentId: "north_america" },
  { name: "Chicago", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "San Francisco", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Los Angeles", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Honolulu", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Cape Town", country: "South Africa", countryCode: "ZA", continentId: "africa" },
  { name: "Kyoto", country: "Japan", countryCode: "JP", continentId: "asia" },
  { name: "Osaka", country: "Japan", countryCode: "JP", continentId: "asia" },
  { name: "Florence", country: "Italy", countryCode: "IT", continentId: "europe" },
  { name: "Venice", country: "Italy", countryCode: "IT", continentId: "europe" },
  { name: "Prague", country: "Czech Republic", countryCode: "CZ", continentId: "europe" },
  { name: "Vienna", country: "Austria", countryCode: "AT", continentId: "europe" },
  { name: "Zurich", country: "Switzerland", countryCode: "CH", continentId: "europe" },
  { name: "Athens", country: "Greece", countryCode: "GR", continentId: "europe" },
  { name: "Stockholm", country: "Sweden", countryCode: "SE", continentId: "europe" },
  { name: "Copenhagen", country: "Denmark", countryCode: "DK", continentId: "europe" },
  { name: "Dublin", country: "Ireland", countryCode: "IE", continentId: "europe" },
  { name: "Auckland", country: "New Zealand", countryCode: "NZ", continentId: "oceania" },
  { name: "Marrakech", country: "Morocco", countryCode: "MA", continentId: "africa" },
  { name: "Saint Louis", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "St. Louis", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Washington D.C.", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Boston", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Seattle", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Miami", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Houston", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Dallas", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Atlanta", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Denver", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Nashville", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "New Orleans", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Philadelphia", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "San Diego", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Austin", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Las Vegas", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Orlando", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Portland", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Minneapolis", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Detroit", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Charlotte", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "San Antonio", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Phoenix", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Pittsburgh", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Kansas City", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Indianapolis", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Cincinnati", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Cleveland", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Columbus", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Milwaukee", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Salt Lake City", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Savannah", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Charleston", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Maui", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Big Island", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Anchorage", country: "United States", countryCode: "US", continentId: "north_america" },
  { name: "Toronto", country: "Canada", countryCode: "CA", continentId: "north_america" },
  { name: "Vancouver", country: "Canada", countryCode: "CA", continentId: "north_america" },
  { name: "Montreal", country: "Canada", countryCode: "CA", continentId: "north_america" },
  { name: "Calgary", country: "Canada", countryCode: "CA", continentId: "north_america" },
  { name: "Ottawa", country: "Canada", countryCode: "CA", continentId: "north_america" },
  { name: "Cancun", country: "Mexico", countryCode: "MX", continentId: "north_america" },
  { name: "Guadalajara", country: "Mexico", countryCode: "MX", continentId: "north_america" },
  { name: "Havana", country: "Cuba", countryCode: "CU", continentId: "north_america" },
  { name: "San Juan", country: "Puerto Rico", countryCode: "PR", continentId: "north_america" },
  { name: "Kingston", country: "Jamaica", countryCode: "JM", continentId: "north_america" },
  { name: "Madrid", country: "Spain", countryCode: "ES", continentId: "europe" },
  { name: "Milan", country: "Italy", countryCode: "IT", continentId: "europe" },
  { name: "Naples", country: "Italy", countryCode: "IT", continentId: "europe" },
  { name: "Munich", country: "Germany", countryCode: "DE", continentId: "europe" },
  { name: "Hamburg", country: "Germany", countryCode: "DE", continentId: "europe" },
  { name: "Edinburgh", country: "United Kingdom", countryCode: "GB", continentId: "europe" },
  { name: "Manchester", country: "United Kingdom", countryCode: "GB", continentId: "europe" },
  { name: "Brussels", country: "Belgium", countryCode: "BE", continentId: "europe" },
  { name: "Oslo", country: "Norway", countryCode: "NO", continentId: "europe" },
  { name: "Helsinki", country: "Finland", countryCode: "FI", continentId: "europe" },
  { name: "Warsaw", country: "Poland", countryCode: "PL", continentId: "europe" },
  { name: "Krakow", country: "Poland", countryCode: "PL", continentId: "europe" },
  { name: "Budapest", country: "Hungary", countryCode: "HU", continentId: "europe" },
  { name: "Dubrovnik", country: "Croatia", countryCode: "HR", continentId: "europe" },
  { name: "Santorini", country: "Greece", countryCode: "GR", continentId: "europe" },
  { name: "Reykjavik", country: "Iceland", countryCode: "IS", continentId: "europe" },
  { name: "Porto", country: "Portugal", countryCode: "PT", continentId: "europe" },
  { name: "Seville", country: "Spain", countryCode: "ES", continentId: "europe" },
  { name: "Nice", country: "France", countryCode: "FR", continentId: "europe" },
  { name: "Lyon", country: "France", countryCode: "FR", continentId: "europe" },
  { name: "Marseille", country: "France", countryCode: "FR", continentId: "europe" },
  { name: "Geneva", country: "Switzerland", countryCode: "CH", continentId: "europe" },
  { name: "Moscow", country: "Russia", countryCode: "RU", continentId: "europe" },
  { name: "St. Petersburg", country: "Russia", countryCode: "RU", continentId: "europe" },
  { name: "Beijing", country: "China", countryCode: "CN", continentId: "asia" },
  { name: "Shanghai", country: "China", countryCode: "CN", continentId: "asia" },
  { name: "Hong Kong", country: "China", countryCode: "HK", continentId: "asia" },
  { name: "Mumbai", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Bangalore", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Jaipur", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Agra", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Goa", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Mysore", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Ooty", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Kochi", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Munnar", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Alleppey", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Varkala", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Pondicherry", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Chennai", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Madurai", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Mahabalipuram", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Coorg", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Hampi", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Hyderabad", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Kolkata", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Varanasi", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Udaipur", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Jodhpur", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Jaisalmer", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Bikaner", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Pushkar", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Mount Abu", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Amritsar", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Ahmedabad", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Pune", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Lonavala", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Rishikesh", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Manali", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Shimla", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Darjeeling", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Leh Ladakh", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Ranthambore", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Tirupati", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Bhubaneswar", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Andaman Islands", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Leh", country: "India", countryCode: "IN", continentId: "asia" },
  { name: "Hanoi", country: "Vietnam", countryCode: "VN", continentId: "asia" },
  { name: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN", continentId: "asia" },
  { name: "Bali", country: "Indonesia", countryCode: "ID", continentId: "asia" },
  { name: "Jakarta", country: "Indonesia", countryCode: "ID", continentId: "asia" },
  { name: "Kuala Lumpur", country: "Malaysia", countryCode: "MY", continentId: "asia" },
  { name: "Taipei", country: "Taiwan", countryCode: "TW", continentId: "asia" },
  { name: "Manila", country: "Philippines", countryCode: "PH", continentId: "asia" },
  { name: "Kathmandu", country: "Nepal", countryCode: "NP", continentId: "asia" },
  { name: "Colombo", country: "Sri Lanka", countryCode: "LK", continentId: "asia" },
  { name: "Phnom Penh", country: "Cambodia", countryCode: "KH", continentId: "asia" },
  { name: "Siem Reap", country: "Cambodia", countryCode: "KH", continentId: "asia" },
  { name: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE", continentId: "asia" },
  { name: "Doha", country: "Qatar", countryCode: "QA", continentId: "asia" },
  { name: "Jerusalem", country: "Israel", countryCode: "IL", continentId: "asia" },
  { name: "Tel Aviv", country: "Israel", countryCode: "IL", continentId: "asia" },
  { name: "Sao Paulo", country: "Brazil", countryCode: "BR", continentId: "south_america" },
  { name: "Bogota", country: "Colombia", countryCode: "CO", continentId: "south_america" },
  { name: "Cartagena", country: "Colombia", countryCode: "CO", continentId: "south_america" },
  { name: "Santiago", country: "Chile", countryCode: "CL", continentId: "south_america" },
  { name: "Cusco", country: "Peru", countryCode: "PE", continentId: "south_america" },
  { name: "Quito", country: "Ecuador", countryCode: "EC", continentId: "south_america" },
  { name: "Montevideo", country: "Uruguay", countryCode: "UY", continentId: "south_america" },
  { name: "Dar es Salaam", country: "Tanzania", countryCode: "TZ", continentId: "africa" },
  { name: "Accra", country: "Ghana", countryCode: "GH", continentId: "africa" },
  { name: "Lagos", country: "Nigeria", countryCode: "NG", continentId: "africa" },
  { name: "Johannesburg", country: "South Africa", countryCode: "ZA", continentId: "africa" },
  { name: "Addis Ababa", country: "Ethiopia", countryCode: "ET", continentId: "africa" },
  { name: "Casablanca", country: "Morocco", countryCode: "MA", continentId: "africa" },
  { name: "Zanzibar", country: "Tanzania", countryCode: "TZ", continentId: "africa" },
  { name: "Melbourne", country: "Australia", countryCode: "AU", continentId: "oceania" },
  { name: "Brisbane", country: "Australia", countryCode: "AU", continentId: "oceania" },
  { name: "Perth", country: "Australia", countryCode: "AU", continentId: "oceania" },
  { name: "Wellington", country: "New Zealand", countryCode: "NZ", continentId: "oceania" },
  { name: "Queenstown", country: "New Zealand", countryCode: "NZ", continentId: "oceania" },
  { name: "Fiji", country: "Fiji", countryCode: "FJ", continentId: "oceania" },
];

export const CITY_COORDS: Record<string, { lat: number; lon: number }> = {
  "paris": { lat: 48.8, lon: 2.3 },
  "london": { lat: 51.5, lon: -0.1 },
  "tokyo": { lat: 35.7, lon: 139.7 },
  "rome": { lat: 41.9, lon: 12.5 },
  "new york": { lat: 40.7, lon: -74.0 },
  "sydney": { lat: -33.9, lon: 151.2 },
  "barcelona": { lat: 41.4, lon: 2.2 },
  "dubai": { lat: 25.2, lon: 55.3 },
  "cairo": { lat: 30.0, lon: 31.2 },
  "rio de janeiro": { lat: -22.9, lon: -43.2 },
  "bangkok": { lat: 13.8, lon: 100.5 },
  "istanbul": { lat: 41.0, lon: 29.0 },
  "amsterdam": { lat: 52.4, lon: 4.9 },
  "berlin": { lat: 52.5, lon: 13.4 },
  "lisbon": { lat: 38.7, lon: -9.1 },
  "singapore": { lat: 1.4, lon: 103.8 },
  "seoul": { lat: 37.6, lon: 127.0 },
  "delhi": { lat: 28.6, lon: 77.2 },
  "nairobi": { lat: -1.3, lon: 36.8 },
  "buenos aires": { lat: -34.6, lon: -58.4 },
  "lima": { lat: -12.0, lon: -77.0 },
  "mexico city": { lat: 19.4, lon: -99.1 },
  "chicago": { lat: 41.9, lon: -87.6 },
  "san francisco": { lat: 37.8, lon: -122.4 },
  "los angeles": { lat: 34.1, lon: -118.2 },
  "honolulu": { lat: 21.3, lon: -157.8 },
  "cape town": { lat: -33.9, lon: 18.4 },
  "kyoto": { lat: 35.0, lon: 135.8 },
  "osaka": { lat: 34.7, lon: 135.5 },
  "florence": { lat: 43.8, lon: 11.3 },
  "venice": { lat: 45.4, lon: 12.3 },
  "prague": { lat: 50.1, lon: 14.4 },
  "vienna": { lat: 48.2, lon: 16.4 },
  "zurich": { lat: 47.4, lon: 8.5 },
  "athens": { lat: 37.98, lon: 23.7 },
  "stockholm": { lat: 59.3, lon: 18.1 },
  "copenhagen": { lat: 55.7, lon: 12.6 },
  "dublin": { lat: 53.3, lon: -6.3 },
  "auckland": { lat: -36.8, lon: 174.8 },
  "marrakech": { lat: 31.6, lon: -8.0 },
  "saint louis": { lat: 38.6, lon: -90.2 },
  "st. louis": { lat: 38.6, lon: -90.2 },
  "washington d.c.": { lat: 38.9, lon: -77.0 },
  "washington dc": { lat: 38.9, lon: -77.0 },
  "boston": { lat: 42.4, lon: -71.1 },
  "seattle": { lat: 47.6, lon: -122.3 },
  "miami": { lat: 25.8, lon: -80.2 },
  "houston": { lat: 29.8, lon: -95.4 },
  "dallas": { lat: 32.8, lon: -96.8 },
  "atlanta": { lat: 33.7, lon: -84.4 },
  "denver": { lat: 39.7, lon: -105.0 },
  "nashville": { lat: 36.2, lon: -86.8 },
  "new orleans": { lat: 30.0, lon: -90.1 },
  "philadelphia": { lat: 39.95, lon: -75.2 },
  "san diego": { lat: 32.7, lon: -117.2 },
  "austin": { lat: 30.3, lon: -97.7 },
  "las vegas": { lat: 36.2, lon: -115.1 },
  "orlando": { lat: 28.5, lon: -81.4 },
  "portland": { lat: 45.5, lon: -122.7 },
  "minneapolis": { lat: 44.98, lon: -93.3 },
  "detroit": { lat: 42.3, lon: -83.0 },
  "charlotte": { lat: 35.2, lon: -80.8 },
  "san antonio": { lat: 29.4, lon: -98.5 },
  "phoenix": { lat: 33.4, lon: -112.1 },
  "pittsburgh": { lat: 40.4, lon: -80.0 },
  "kansas city": { lat: 39.1, lon: -94.6 },
  "indianapolis": { lat: 39.8, lon: -86.2 },
  "cincinnati": { lat: 39.1, lon: -84.5 },
  "cleveland": { lat: 41.5, lon: -81.7 },
  "columbus": { lat: 40.0, lon: -83.0 },
  "milwaukee": { lat: 43.0, lon: -87.9 },
  "salt lake city": { lat: 40.8, lon: -111.9 },
  "savannah": { lat: 32.1, lon: -81.1 },
  "charleston": { lat: 32.8, lon: -79.9 },
  "maui": { lat: 20.8, lon: -156.3 },
  "big island": { lat: 19.5, lon: -155.5 },
  "anchorage": { lat: 61.2, lon: -149.9 },
  "toronto": { lat: 43.7, lon: -79.4 },
  "vancouver": { lat: 49.3, lon: -123.1 },
  "montreal": { lat: 45.5, lon: -73.6 },
  "calgary": { lat: 51.0, lon: -114.1 },
  "ottawa": { lat: 45.4, lon: -75.7 },
  "cancun": { lat: 21.2, lon: -86.8 },
  "guadalajara": { lat: 20.7, lon: -103.3 },
  "havana": { lat: 23.1, lon: -82.4 },
  "san juan": { lat: 18.5, lon: -66.1 },
  "kingston": { lat: 18.0, lon: -76.8 },
  "madrid": { lat: 40.4, lon: -3.7 },
  "milan": { lat: 45.5, lon: 9.2 },
  "naples": { lat: 40.9, lon: 14.3 },
  "munich": { lat: 48.1, lon: 11.6 },
  "hamburg": { lat: 53.6, lon: 10.0 },
  "edinburgh": { lat: 55.95, lon: -3.2 },
  "manchester": { lat: 53.5, lon: -2.2 },
  "brussels": { lat: 50.8, lon: 4.4 },
  "oslo": { lat: 59.9, lon: 10.8 },
  "helsinki": { lat: 60.2, lon: 24.9 },
  "warsaw": { lat: 52.2, lon: 21.0 },
  "krakow": { lat: 50.1, lon: 19.9 },
  "budapest": { lat: 47.5, lon: 19.0 },
  "dubrovnik": { lat: 42.6, lon: 18.1 },
  "santorini": { lat: 36.4, lon: 25.4 },
  "reykjavik": { lat: 64.1, lon: -21.9 },
  "porto": { lat: 41.2, lon: -8.6 },
  "seville": { lat: 37.4, lon: -6.0 },
  "nice": { lat: 43.7, lon: 7.3 },
  "lyon": { lat: 45.8, lon: 4.8 },
  "marseille": { lat: 43.3, lon: 5.4 },
  "geneva": { lat: 46.2, lon: 6.1 },
  "moscow": { lat: 55.8, lon: 37.6 },
  "st. petersburg": { lat: 59.9, lon: 30.3 },
  "beijing": { lat: 39.9, lon: 116.4 },
  "shanghai": { lat: 31.2, lon: 121.5 },
  "hong kong": { lat: 22.3, lon: 114.2 },
  "mumbai": { lat: 19.1, lon: 72.9 },
  "bangalore": { lat: 12.97, lon: 77.6 },
  "bengaluru": { lat: 12.97, lon: 77.6 },
  "mysore": { lat: 12.31, lon: 76.65 },
  "mysuru": { lat: 12.31, lon: 76.65 },
  "mysore, karnataka": { lat: 12.31, lon: 76.65 },
  "ooty": { lat: 11.41, lon: 76.69 },
  "ootacamund": { lat: 11.41, lon: 76.69 },
  "ooty, tamil nadu": { lat: 11.41, lon: 76.69 },
  "coorg": { lat: 12.42, lon: 75.74 },
  "goa": { lat: 15.30, lon: 74.12 },
  "kochi": { lat: 9.93, lon: 76.27 },
  "cochin": { lat: 9.93, lon: 76.27 },
  "udaipur": { lat: 24.58, lon: 73.71 },
  "varanasi": { lat: 25.35, lon: 82.97 },
  "amritsar": { lat: 31.63, lon: 74.87 },
  "darjeeling": { lat: 27.04, lon: 88.26 },
  "shimla": { lat: 31.10, lon: 77.17 },
  "manali": { lat: 32.24, lon: 77.19 },
  "rishikesh": { lat: 30.09, lon: 78.27 },
  "leh": { lat: 34.16, lon: 77.58 },
  "leh ladakh": { lat: 34.16, lon: 77.58 },
  "jodhpur": { lat: 26.29, lon: 73.02 },
  "jaisalmer": { lat: 26.91, lon: 70.92 },
  "pushkar": { lat: 26.49, lon: 74.56 },
  "hampi": { lat: 15.34, lon: 76.46 },
  "alleppey": { lat: 9.50, lon: 76.36 },
  "munnar": { lat: 10.09, lon: 77.06 },
  "pondicherry": { lat: 11.93, lon: 79.83 },
  "madurai": { lat: 9.92, lon: 78.12 },
  "pune": { lat: 18.52, lon: 73.86 },
  "hyderabad": { lat: 17.39, lon: 78.49 },
  "chennai": { lat: 13.08, lon: 80.27 },
  "kolkata": { lat: 22.57, lon: 88.36 },
  "ahmedabad": { lat: 23.03, lon: 72.59 },
  "lonavala": { lat: 18.75, lon: 73.40 },
  "mahabaleshwar": { lat: 17.93, lon: 73.66 },
  "mahabaleshwar, india": { lat: 17.93, lon: 73.66 },
  "mahabaleshwar, maharashtra": { lat: 17.93, lon: 73.66 },
  "mahableshwar": { lat: 17.93, lon: 73.66 },
  "matheran": { lat: 18.98, lon: 73.27 },
  "matheran, india": { lat: 18.98, lon: 73.27 },
  "mahabalipuram": { lat: 12.62, lon: 80.19 },
  "tirupati": { lat: 13.63, lon: 79.42 },
  "bhubaneswar": { lat: 20.30, lon: 85.82 },
  "bikaner": { lat: 28.02, lon: 73.31 },
  "mount abu": { lat: 24.59, lon: 72.71 },
  "varkala": { lat: 8.73, lon: 76.72 },
  "ranthambore": { lat: 26.01, lon: 76.50 },
  "andaman islands": { lat: 11.67, lon: 92.74 },
  "andaman": { lat: 11.67, lon: 92.74 },
  "jaipur": { lat: 26.9, lon: 75.8 },
  "agra": { lat: 27.2, lon: 78.0 },
  "hanoi": { lat: 21.0, lon: 105.9 },
  "ho chi minh city": { lat: 10.8, lon: 106.7 },
  "bali": { lat: -8.4, lon: 115.2 },
  "jakarta": { lat: -6.2, lon: 106.8 },
  "kuala lumpur": { lat: 3.1, lon: 101.7 },
  "taipei": { lat: 25.0, lon: 121.5 },
  "manila": { lat: 14.6, lon: 121.0 },
  "kathmandu": { lat: 27.7, lon: 85.3 },
  "colombo": { lat: 6.9, lon: 79.9 },
  "phnom penh": { lat: 11.6, lon: 104.9 },
  "siem reap": { lat: 13.4, lon: 103.9 },
  "abu dhabi": { lat: 24.5, lon: 54.7 },
  "doha": { lat: 25.3, lon: 51.5 },
  "jerusalem": { lat: 31.8, lon: 35.2 },
  "tel aviv": { lat: 32.1, lon: 34.8 },
  "sao paulo": { lat: -23.6, lon: -46.6 },
  "bogota": { lat: 4.7, lon: -74.1 },
  "cartagena": { lat: 10.4, lon: -75.5 },
  "santiago": { lat: -33.4, lon: -70.7 },
  "cusco": { lat: -13.5, lon: -72.0 },
  "quito": { lat: -0.2, lon: -78.5 },
  "montevideo": { lat: -34.9, lon: -56.2 },
  "dar es salaam": { lat: -6.8, lon: 39.3 },
  "accra": { lat: 5.6, lon: -0.2 },
  "lagos": { lat: 6.5, lon: 3.4 },
  "johannesburg": { lat: -26.2, lon: 28.0 },
  "addis ababa": { lat: 9.0, lon: 38.7 },
  "casablanca": { lat: 33.6, lon: -7.6 },
  "zanzibar": { lat: -6.2, lon: 39.2 },
  "melbourne": { lat: -37.8, lon: 145.0 },
  "brisbane": { lat: -27.5, lon: 153.0 },
  "perth": { lat: -31.95, lon: 115.9 },
  "wellington": { lat: -41.3, lon: 174.8 },
  "queenstown": { lat: -45.0, lon: 168.7 },
  "fiji": { lat: -17.8, lon: 178.0 },
  "south africa": { lat: -30.6, lon: 22.9 },
  "egypt": { lat: 26.8, lon: 30.8 },
  "kenya": { lat: -0.02, lon: 37.9 },
  "morocco": { lat: 31.8, lon: -7.1 },
  "tanzania": { lat: -6.4, lon: 34.9 },
  "japan": { lat: 36.2, lon: 138.3 },
  "china": { lat: 35.9, lon: 104.2 },
  "india": { lat: 20.6, lon: 79.0 },
  "thailand": { lat: 15.9, lon: 100.9 },
  "united kingdom": { lat: 55.4, lon: -3.4 },
  "france": { lat: 46.2, lon: 2.2 },
  "germany": { lat: 51.2, lon: 10.5 },
  "italy": { lat: 41.9, lon: 12.6 },
  "spain": { lat: 40.5, lon: -3.7 },
  "united states": { lat: 37.1, lon: -95.7 },
  "canada": { lat: 56.1, lon: -106.3 },
  "mexico": { lat: 23.6, lon: -102.5 },
  "brazil": { lat: -14.2, lon: -51.9 },
  "australia": { lat: -25.3, lon: 133.8 },
  "new zealand": { lat: -40.9, lon: 174.9 },
  "argentina": { lat: -38.4, lon: -63.6 },
  "peru": { lat: -9.2, lon: -75.0 },
  "colombia": { lat: 4.6, lon: -74.3 },
  "chile": { lat: -35.7, lon: -71.5 },
  "karachi": { lat: 24.86, lon: 67.01 },
  "lahore": { lat: 31.55, lon: 74.35 },
  "islamabad": { lat: 33.72, lon: 73.06 },
  "dhaka": { lat: 23.81, lon: 90.41 },
  "yangon": { lat: 16.85, lon: 96.19 },
  "dakar": { lat: 14.72, lon: -17.47 },
  "tunis": { lat: 36.82, lon: 10.18 },
  "algiers": { lat: 36.74, lon: 3.06 },
  "tripoli": { lat: 32.9, lon: 13.18 },
  "khartoum": { lat: 15.55, lon: 32.53 },
  "kampala": { lat: 0.35, lon: 32.58 },
  "lusaka": { lat: -15.42, lon: 28.28 },
  "harare": { lat: -17.82, lon: 31.05 },
  "antananarivo": { lat: -18.91, lon: 47.54 },
  "suva": { lat: -18.14, lon: 178.44 },
  "nadi": { lat: -17.79, lon: 177.44 },
  "apia": { lat: -13.83, lon: -171.77 },
  "port moresby": { lat: -9.44, lon: 147.18 },
  "busan": { lat: 35.1, lon: 129.04 },
  "ulaanbaatar": { lat: 47.91, lon: 106.88 },
  "tashkent": { lat: 41.3, lon: 69.27 },
  "almaty": { lat: 43.25, lon: 76.95 },
  "baku": { lat: 40.41, lon: 49.87 },
  "tbilisi": { lat: 41.69, lon: 44.83 },
  "yerevan": { lat: 40.18, lon: 44.51 },
  "beirut": { lat: 33.89, lon: 35.5 },
  "baghdad": { lat: 33.34, lon: 44.4 },
  "amman": { lat: 31.96, lon: 35.95 },
  "riyadh": { lat: 24.69, lon: 46.72 },
  "muscat": { lat: 23.59, lon: 58.59 },
  "tehran": { lat: 35.69, lon: 51.39 },
  "kabul": { lat: 34.53, lon: 69.17 },
  "caracas": { lat: 10.49, lon: -66.88 },
  "giza": { lat: 29.98, lon: 31.13 },
  "quebec city": { lat: 46.81, lon: -71.21 },
  "africa": { lat: 8.8, lon: 34.5 },
  "asia": { lat: 34.0, lon: 100.6 },
  "europe": { lat: 54.5, lon: 15.3 },
  "north america": { lat: 54.5, lon: -105.3 },
  "south america": { lat: -8.8, lon: -55.5 },
  "oceania": { lat: -22.7, lon: 140.0 },
};

export function getCoordsForName(name: string): { lat: number; lon: number } | null {
  return CITY_COORDS[name.toLowerCase()] || null;
}
