uploads = []

[[generated]]
id = "-zcWQfHLVsfGL7oWNX3aN"
uri = "file://artifacts/roamus-mobile/assets/images/icon.png"
type = "image"
title = "roamus app icon"

[[outputs]]
id = "46i2sXu8azDNeineplpXk"
uri = "file://roamus-source.zip"
type = "unspecified"
title = "RoamUs Source Code"

[[outputs]]
id = "qZMaOBXQ7TwtxFl1onNSv"
uri = "file://roamus-ts-source.zip"
type = "unspecified"
title = "RoamUs TypeScript Source Files"

[[outputs]]
id = "MAb4EsipT_JQD4wIEn5om"
uri = "file://reports/chicago-qa-audit-2026-06-11.md"
type = "text"
title = "Chicago QA Audit — 2026-06-11"

[[outputs]]
id = "Ov-zVxY5R5Twh6n1Uniew"
uri = "file://attached_assets/roamus-logo-transparent.png"
type = "image"
title = "RoamUs Logo — Transparent Background"
