import { useLocation } from "wouter";

export default function PrivacyPolicy() {
  const [, setLocation] = useLocation();

  return (
    <div style={{ fontFamily: "'Plus Jakarta Sans', sans-serif", background: "#F5F2EE", color: "#1A1F2E", minHeight: "100vh", lineHeight: 1.7, WebkitFontSmoothing: "antialiased" }}>
      <nav style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "16px 24px", borderBottom: "1px solid rgba(26,31,46,0.10)", background: "#F5F2EE" }}>
        <a href="/" style={{ fontFamily: "'Fraunces', serif", fontSize: 20, fontWeight: 700, color: "#E8692A", textDecoration: "none" }}>RoamUs</a>
        <a href="/" onClick={(e) => { e.preventDefault(); if (window.history.length > 1) { window.history.back(); } else { setLocation("/"); } }} style={{ fontSize: 14, color: "#8A8FA8", textDecoration: "none", display: "flex", alignItems: "center", gap: 6 }}>← Back to home</a>
      </nav>

      <div style={{ maxWidth: 720, margin: "0 auto", padding: "56px 24px 80px" }}>
        <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: ".15em", color: "#E8692A", textTransform: "uppercase", marginBottom: 12 }}>Legal</div>
        <h1 style={{ fontFamily: "'Fraunces', serif", fontSize: 38, fontWeight: 700, letterSpacing: "-.8px", marginBottom: 8 }}>Privacy Policy</h1>
        <p style={{ fontSize: 13, color: "#8A8FA8", marginBottom: 48 }}>Last updated: January 1, 2026 · Effective immediately</p>

        <Section title="1. Overview">
          <p>This Privacy Policy explains how RoamUs ("RoamUs," "we," "our," or "us"), a product of GeoQuest Games LLC, collects, uses, and protects personal information when parents, children, and families use our mobile application and related services (the "Services").</p>
          <p>RoamUs is a family travel companion app. We are committed to transparent, parent-friendly data practices. We comply with the Children's Online Privacy Protection Act (COPPA) and applicable privacy laws. Parents are always in control of their family's account and information.</p>
          <p><strong>The short version:</strong> We collect what we need to run your family's trips. We don't sell your data. We don't share it for advertising. You can delete everything anytime.</p>
        </Section>

        <Section title="2. Information We Collect">
          <h3 style={h3Style}>Information provided by parents during signup</h3>
          <ul style={ulStyle}>
            <li>Email address</li>
            <li>Password (encrypted and stored securely — we never see it in plain text)</li>
            <li>Parent name (optional)</li>
          </ul>
          <h3 style={h3Style}>Information about children (entered by parents only)</h3>
          <ul style={ulStyle}>
            <li>Child's first name</li>
            <li>Child's age or age range</li>
            <li>Profile avatar</li>
          </ul>
          <p>Children cannot create accounts or enter their own information. All child profiles are created and managed by parents.</p>
          <h3 style={h3Style}>Trip and travel data (created during use)</h3>
          <ul style={ulStyle}>
            <li>Destinations, itineraries, and trip plans</li>
            <li>Stop visits, times, and completion status</li>
            <li>Explorer missions completed and XP earned</li>
            <li>Family journal entries, reflections, and kid responses</li>
            <li>Photos uploaded or captured during trips (stored in your account only)</li>
            <li>Trip stories and memories generated by the app</li>
            <li>Preferences (trip pace, adventure style, traveler details)</li>
          </ul>
          <h3 style={h3Style}>Location information</h3>
          <p>RoamUs uses location data to power the core experience — showing you relevant stop information, navigation, and context as your family moves through a destination.</p>
          <ul style={ulStyle}>
            <li><strong>Approximate GPS (while using the app)</strong> — Show nearby stops, trigger stop-arrival notifications, provide directions</li>
            <li><strong>Destination city/region (entered by parent)</strong> — Generate trip itinerary and stop content</li>
          </ul>
          <p>Location is used only while the app is actively in use. We do not track location in the background or store movement history. You can disable location access at any time in your device settings — some features will be unavailable without it.</p>
          <h3 style={h3Style}>Push notifications</h3>
          <p>With your permission, RoamUs sends push notifications to enhance the trip experience — including stop arrival reminders, mission prompts for kids, and daily check-ins. You can manage or disable notifications in your device settings at any time.</p>
          <h3 style={h3Style}>Technical data collected automatically</h3>
          <ul style={ulStyle}>
            <li>Device type and operating system version</li>
            <li>App version</li>
            <li>Anonymous usage statistics (which features are used, crash reports)</li>
            <li>Session timing (for performance monitoring)</li>
          </ul>
          <p>This data is never linked to your identity and is used only to improve app stability and performance.</p>
          <h3 style={h3Style}>What we do NOT collect</h3>
          <ul style={ulStyle}>
            <li>Continuous or background GPS tracking</li>
            <li>Audio or video recordings</li>
            <li>Biometric identifiers</li>
            <li>Behavioral advertising profiles</li>
            <li>Contacts, calendar, or other device data not related to RoamUs</li>
            <li>Financial data (payments are processed by Stripe — we never see your card details)</li>
          </ul>
        </Section>

        <Section title="3. How We Use Your Information">
          <ul style={ulStyle}>
            <li>Create and manage your family account</li>
            <li>Generate trip itineraries and stop recommendations</li>
            <li>Power the Run layer — delivering real-time stop guidance during your trip</li>
            <li>Deliver kids' missions and track explorer progress</li>
            <li>Generate your family's trip story and memory at the end of a trip</li>
            <li>Enable offline access by caching trip data on your device</li>
            <li>Send push notifications you've opted into</li>
            <li>Process subscription and trip pack payments via Stripe</li>
            <li>Improve app performance and fix bugs</li>
            <li>Communicate with parents about account updates</li>
          </ul>
          <p>We do not sell personal data. We do not use your data for behavioral advertising.</p>
        </Section>

        <Section title="4. Offline Access and Data Caching">
          <p>A core feature of RoamUs is offline access. When you build a trip and go online before traveling, RoamUs caches your itinerary, stop details, and media locally on your device. This data remains on your device until you clear it or delete the app.</p>
          <p>Offline data includes: stop names, descriptions, addresses, timing, missions, and any pre-downloaded images. It does not include other users' data or payment information.</p>
        </Section>

        <Section title="5. Children's Privacy and COPPA Compliance">
          <h3 style={h3Style}>Parental consent and control</h3>
          <ul style={ulStyle}>
            <li>Parents must create the account and provide consent</li>
            <li>All child information is entered by a parent</li>
            <li>Children cannot create accounts independently</li>
            <li>Children interact with missions and content through parent-managed profiles</li>
          </ul>
          <h3 style={h3Style}>Child safety by design</h3>
          <ul style={ulStyle}>
            <li>Children cannot access external websites from within RoamUs</li>
            <li>No in-app chat, messaging, or social interaction between users</li>
            <li>Children cannot submit content visible to other families</li>
            <li>Kid mission responses are stored only within the family's private account</li>
          </ul>
          <h3 style={h3Style}>Trip story sharing — parent controlled</h3>
          <p>When a trip ends, RoamUs generates an auto-story with your family's photos, moments, and route. Sharing this story is entirely parent-initiated. Children cannot share content independently.</p>
          <p>When a parent chooses to share content externally (e.g., to WhatsApp, Instagram, or email), shared content is governed by the policies of the receiving platform. RoamUs does not share personal data alongside shared story content.</p>
          <h3 style={h3Style}>Parental rights</h3>
          <p>Parents may at any time:</p>
          <ul style={ulStyle}>
            <li>Review all data associated with their account</li>
            <li>Update or correct account information</li>
            <li>Request deletion of their account and all associated data</li>
            <li>Withdraw consent for data collection</li>
            <li>Disable location services or push notifications via device settings</li>
          </ul>
          <p>Contact us at: <a href="mailto:privacy@roamus.app" style={linkStyle}>privacy@roamus.app</a></p>
        </Section>

        <Section title="6. Third-Party Services">
          <ul style={ulStyle}>
            <li><strong>Stripe</strong> — Payment processing (payment details only; we never see card numbers)</li>
            <li><strong>OpenAI</strong> — AI-generated trip content, stop stories, trip narratives (destination and preference data only; no personal identity)</li>
            <li><strong>Google Analytics</strong> — Anonymous app performance monitoring (anonymous usage statistics only)</li>
            <li><strong>ElevenLabs / Google TTS</strong> — Text-to-speech audio for stop content (stop text content only)</li>
            <li><strong>Neon PostgreSQL</strong> — Database hosting (all account and trip data, encrypted at rest)</li>
          </ul>
          <p>We do not use advertising networks. We do not share data with data brokers.</p>
        </Section>

        <Section title="7. Subscriptions and Billing">
          <p>RoamUs offers a monthly subscription (GeoPass) and per-trip purchases (Trip Pack) processed through Stripe. Subscription billing is recurring and can be cancelled at any time through the app or by contacting us. Cancellation takes effect at the end of the current billing period.</p>
          <p>For App Store purchases, billing and refund management are handled by Apple in accordance with their terms.</p>
        </Section>

        <Section title="8. Cookies and Tracking">
          <p>The RoamUs mobile app does not use browser cookies. On the web (roamus.app), we use minimal cookies for:</p>
          <ul style={ulStyle}>
            <li>Login session management</li>
            <li>Basic anonymous analytics</li>
          </ul>
          <p>We do not use tracking cookies for advertising.</p>
        </Section>

        <Section title="9. Data Security">
          <p>We use industry-standard security measures including:</p>
          <ul style={ulStyle}>
            <li>HTTPS encryption for all data in transit</li>
            <li>Encrypted password storage (bcrypt)</li>
            <li>Database encryption at rest</li>
            <li>Access controls limiting data access to authorized personnel</li>
          </ul>
          <p>No system is 100% secure. In the event of a data breach affecting your personal information, we will notify you as required by applicable law.</p>
        </Section>

        <Section title="10. Data Retention">
          <p>We retain your account data for as long as your account is active or as needed to provide services. Trip data, memories, and photos are retained indefinitely to preserve your family's travel history — unless you delete them.</p>
          <p>Parents may request deletion of their full account and all associated data at any time by emailing <a href="mailto:privacy@roamus.app" style={linkStyle}>privacy@roamus.app</a>. We will delete data within 30 days of a verified request.</p>
        </Section>

        <Section title="11. International Users">
          <p>RoamUs is operated from the United States. If you are located outside the US (including India), your data is transferred to and processed in the US. By using RoamUs, you consent to this transfer.</p>
          <p>We offer regional pricing for India (₹) and aim to comply with applicable data protection requirements in all markets we serve.</p>
        </Section>

        <Section title="12. Changes to This Policy">
          <p>We may update this Privacy Policy from time to time. We will notify parents of material changes through the app or by email at least 14 days before changes take effect. Continued use of RoamUs after that date constitutes acceptance of the updated policy.</p>
        </Section>

        <Section title="13. Contact Us">
          <p>RoamUs (a product of GeoQuest Games LLC)</p>
          <p>Email: <a href="mailto:privacy@roamus.app" style={linkStyle}>privacy@roamus.app</a></p>
          <p>Support: <a href="mailto:hello@roamus.app" style={linkStyle}>hello@roamus.app</a></p>
        </Section>

        <div style={{ background: "rgba(232,105,42,.08)", borderLeft: "3px solid #E8692A", borderRadius: "0 8px 8px 0", padding: "16px 20px", margin: "32px 0" }}>
          <p style={{ margin: 0, fontSize: 14, fontWeight: 600 }}>The RoamUs Family Promise</p>
          <p style={{ margin: "8px 0 0", fontSize: 14 }}>RoamUs is built to be parent-controlled and family-first, free from behavioral advertising, transparent about what we collect and why, and worthy of the trust families place in us on their trips.</p>
          <p style={{ margin: "8px 0 0", fontSize: 14 }}>We do not sell family data. We do not monetize your children's information. Our business model is simple: you pay for the product, the product works for you.</p>
        </div>

        <p style={{ marginTop: 48, fontSize: 13, color: "#8A8FA8" }}>© 2026 GeoQuest Games LLC. All rights reserved.</p>
      </div>
    </div>
  );
}

const h3Style: React.CSSProperties = { fontSize: 16, fontWeight: 600, color: "#1A1F2E", margin: "24px 0 10px" };
const ulStyle: React.CSSProperties = { paddingLeft: 20, marginBottom: 14 };
const linkStyle: React.CSSProperties = { color: "#E8692A", textDecoration: "none" };

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 8 }}>
      <h2 style={{ fontSize: 20, fontWeight: 600, color: "#1A1F2E", margin: "40px 0 14px", paddingTop: 12, borderTop: "1px solid rgba(26,31,46,0.10)" }}>{title}</h2>
      <div style={{ fontSize: 15, color: "#3d4255" }}>{children}</div>
    </div>
  );
}
