import { useState, useEffect, useCallback, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { apiRequest } from "@/lib/queryClient";
import { useExplorer } from "@/lib/explorerContext";
import { Sparkles, Star, Trophy, HelpCircle, Check, X, ChevronRight, Brain, MapPin } from "lucide-react";
import confetti from "canvas-confetti";

interface TrailTalesRiddle {
  id: string;
  tripId: string;
  stopId: string;
  riddleText: string;
  riddleType: string;
  answer: string;
  answerOptions: string[];
  photoHint?: string;
  difficulty: string;
  isUnlocked: boolean;
  unlockedAt?: string;
}

interface TrailTalesAttempt {
  riddleId: string;
  isCorrect: boolean;
  selectedAnswer: string;
}

interface TrailTalesProgress {
  totalRiddles: number;
  correctAnswers: number;
  totalMemoryStars: number;
  isMemoryChampion: boolean;
}

interface TrailTalesGameProps {
  tripId: string;
  tripName: string;
  isOpen: boolean;
  onClose: () => void;
}

export function TrailTalesGame({ tripId, tripName, isOpen, onClose }: TrailTalesGameProps) {
  const { activeExplorer } = useExplorer();
  const [riddles, setRiddles] = useState<TrailTalesRiddle[]>([]);
  const [attempts, setAttempts] = useState<TrailTalesAttempt[]>([]);
  const [progress, setProgress] = useState<TrailTalesProgress | null>(null);
  const [currentRiddleIndex, setCurrentRiddleIndex] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<string | null>(null);
  const [showResult, setShowResult] = useState(false);
  const [lastResult, setLastResult] = useState<{ isCorrect: boolean; correctAnswer: string; starsEarned: number; isReplay?: boolean } | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [gameCompleted, setGameCompleted] = useState(false);

  const hasAutoGeneratedRef = useRef(false);
  
  const loadGameData = useCallback(async () => {
    if (!tripId || !activeExplorer) return;
    
    setIsLoading(true);
    try {
      const riddlesRes = await apiRequest("GET", `/api/travel/trips/${tripId}/trail-tales/riddles`);
      let riddlesData = await riddlesRes.json();
      
      // If no riddles exist and we haven't auto-generated yet, generate them
      if (Array.isArray(riddlesData) && riddlesData.length === 0 && !hasAutoGeneratedRef.current) {
        hasAutoGeneratedRef.current = true;
        console.log("No riddles found, auto-generating...");
        try {
          const genRes = await apiRequest("POST", `/api/travel/trips/${tripId}/trail-tales/generate`);
          const genData = await genRes.json();
          riddlesData = genData.riddles || [];
        } catch (genError) {
          console.error("Error auto-generating riddles:", genError);
          riddlesData = [];
        }
      }
      
      setRiddles(riddlesData);
      
      // Fetch progress after riddles are set (in case generation created new riddles)
      const progressRes = await apiRequest("GET", `/api/travel/trips/${tripId}/trail-tales/progress/${activeExplorer.id}`);
      const progressData = await progressRes.json();
      
      setProgress(progressData.progress);
      setAttempts(progressData.attempts || []);
      
      if (progressData.progress?.isMemoryChampion) {
        setGameCompleted(true);
      }
    } catch (error) {
      console.error("Error loading Trail Tales data:", error);
    } finally {
      setIsLoading(false);
    }
  }, [tripId, activeExplorer]);

  useEffect(() => {
    if (isOpen) {
      setCurrentRiddleIndex(0);
      setSelectedAnswer(null);
      setShowResult(false);
      setLastResult(null);
      setGameCompleted(false);
      loadGameData();
    }
  }, [isOpen, loadGameData]);

  // Reset auto-generation flag when trip changes
  useEffect(() => {
    hasAutoGeneratedRef.current = false;
  }, [tripId]);

  const generateRiddles = async () => {
    try {
      setIsLoading(true);
      const res = await apiRequest("POST", `/api/travel/trips/${tripId}/trail-tales/generate`);
      const data = await res.json();
      setRiddles(data.riddles);
    } catch (error) {
      console.error("Error generating riddles:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const submitAnswer = async () => {
    if (!selectedAnswer || !activeExplorer) return;
    
    const currentRiddle = riddles[currentRiddleIndex];
    if (!currentRiddle) return;
    
    setIsSubmitting(true);
    
    try {
      const res = await apiRequest("POST", `/api/travel/trail-tales/riddles/${currentRiddle.id}/answer`, {
        explorerId: activeExplorer.id,
        selectedAnswer
      });
      
      const result = await res.json();
      const isReplay = result.isReplay === true;
      
      setLastResult({
        isCorrect: result.isCorrect,
        correctAnswer: result.correctAnswer,
        starsEarned: result.starsEarned,
        isReplay
      });
      setShowResult(true);
      
      if (result.isCorrect) {
        confetti({
          particleCount: 50,
          spread: 60,
          origin: { y: 0.6 }
        });
      }
      
      if (result.isMemoryChampion) {
        setTimeout(() => {
          setGameCompleted(true);
          confetti({
            particleCount: 100,
            spread: 100,
            origin: { y: 0.5 }
          });
        }, 1500);
      }
      
      // Only update local state for first attempts, not replays
      if (!isReplay) {
        setAttempts(prev => [...prev, {
          riddleId: currentRiddle.id,
          isCorrect: result.isCorrect,
          selectedAnswer
        }]);
        
        setProgress(prev => prev ? {
          ...prev,
          correctAnswers: result.isCorrect ? prev.correctAnswers + 1 : prev.correctAnswers,
          totalMemoryStars: prev.totalMemoryStars + result.starsEarned,
          isMemoryChampion: result.isMemoryChampion
        } : null);
      }
      
    } catch (error) {
      console.error("Error submitting answer:", error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const nextRiddle = () => {
    setShowResult(false);
    setSelectedAnswer(null);
    setLastResult(null);
    
    if (currentRiddleIndex < riddles.length - 1) {
      setCurrentRiddleIndex(prev => prev + 1);
    } else {
      setGameCompleted(true);
    }
  };

  const playAgain = () => {
    setCurrentRiddleIndex(0);
    setSelectedAnswer(null);
    setShowResult(false);
    setLastResult(null);
    setGameCompleted(false);
  };

  const currentRiddle = riddles[currentRiddleIndex];
  const hasAttempted = currentRiddle && attempts.some(a => a.riddleId === currentRiddle.id);
  const currentAttempt = currentRiddle ? attempts.find(a => a.riddleId === currentRiddle.id) : null;
  const hasPlayedBefore = attempts.length > 0;

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-xl">
            <Brain className="w-6 h-6 text-purple-500" />
            Trail Tales
          </DialogTitle>
          <p className="text-sm text-muted-foreground">{tripName}</p>
        </DialogHeader>

        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-12 gap-4">
            <motion.div
              animate={{ rotate: 360 }}
              transition={{ repeat: Infinity, duration: 2, ease: "linear" }}
            >
              <Sparkles className="w-10 h-10 text-purple-500" />
            </motion.div>
            <p className="text-muted-foreground">Loading riddles...</p>
          </div>
        ) : gameCompleted ? (
          <motion.div
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="text-center py-8"
          >
            <motion.div
              animate={{ scale: [1, 1.1, 1] }}
              transition={{ repeat: Infinity, duration: 2 }}
              className="inline-block mb-4"
            >
              <Trophy className="w-20 h-20 text-yellow-500 mx-auto" />
            </motion.div>
            
            {progress?.isMemoryChampion && (
              <motion.div
                initial={{ y: 20, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ delay: 0.3 }}
                className="mb-6"
              >
                <h3 className="text-2xl font-bold text-purple-600 mb-2">Memory Champion!</h3>
                <p className="text-muted-foreground">You answered all riddles correctly!</p>
              </motion.div>
            )}
            
            <div className="flex justify-center gap-1 mb-6">
              {Array.from({ length: progress?.totalMemoryStars || 0 }).map((_, i) => (
                <motion.div
                  key={i}
                  initial={{ scale: 0, rotate: -180 }}
                  animate={{ scale: 1, rotate: 0 }}
                  transition={{ delay: 0.5 + i * 0.1 }}
                >
                  <Star className="w-8 h-8 text-yellow-400 fill-yellow-400" />
                </motion.div>
              ))}
            </div>
            
            <p className="text-lg font-medium mb-2">
              {progress?.correctAnswers || 0} / {progress?.totalRiddles || riddles.length} Correct
            </p>
            <p className="text-sm text-muted-foreground mb-4">
              {progress?.totalMemoryStars || 0} Memory Stars Earned
            </p>
            
            <div className="flex gap-3 justify-center">
              <Button onClick={playAgain} variant="outline" className="border-purple-500 text-purple-600">
                Play Again
              </Button>
              <Button onClick={onClose} className="bg-purple-600 hover:bg-purple-700">
                Close
              </Button>
            </div>
            {hasPlayedBefore && (
              <p className="text-xs text-muted-foreground mt-4">
                Note: Stars are only earned on your first attempt
              </p>
            )}
          </motion.div>
        ) : riddles.length === 0 ? (
          <div className="text-center py-8">
            <HelpCircle className="w-16 h-16 text-muted-foreground mx-auto mb-4" />
            <h3 className="text-lg font-medium mb-2">No Riddles Yet</h3>
            <p className="text-sm text-muted-foreground mb-6">
              Visit more stops to unlock Trail Tales riddles!
            </p>
            <Button onClick={generateRiddles} variant="outline">
              Generate Riddles
            </Button>
          </div>
        ) : (
          <div className="space-y-6">
            <div className="flex items-center justify-between text-sm text-muted-foreground">
              <span>Riddle {currentRiddleIndex + 1} of {riddles.length}</span>
              <div className="flex items-center gap-1">
                <Star className="w-4 h-4 text-yellow-500" />
                <span>{progress?.totalMemoryStars || 0} stars</span>
              </div>
            </div>

            <AnimatePresence mode="wait">
              {showResult && lastResult ? (
                <motion.div
                  key="result"
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  className="text-center py-6"
                >
                  {lastResult.isCorrect ? (
                    <>
                      <motion.div
                        initial={{ scale: 0 }}
                        animate={{ scale: 1 }}
                        transition={{ type: "spring" }}
                        className="mb-4"
                      >
                        <Check className="w-16 h-16 text-green-500 mx-auto" />
                      </motion.div>
                      <h3 className="text-xl font-bold text-green-600 mb-2">Correct!</h3>
                      {lastResult.isReplay ? (
                        <p className="text-sm text-muted-foreground mb-4">
                          Great memory! (Stars already earned)
                        </p>
                      ) : (
                        <div className="flex justify-center gap-1 mb-4">
                          {Array.from({ length: lastResult.starsEarned }).map((_, i) => (
                            <motion.div
                              key={i}
                              initial={{ scale: 0, rotate: -180 }}
                              animate={{ scale: 1, rotate: 0 }}
                              transition={{ delay: 0.2 + i * 0.1 }}
                            >
                              <Star className="w-8 h-8 text-yellow-400 fill-yellow-400" />
                            </motion.div>
                          ))}
                        </div>
                      )}
                    </>
                  ) : (
                    <>
                      <motion.div
                        initial={{ scale: 0 }}
                        animate={{ scale: 1 }}
                        className="mb-4"
                      >
                        <X className="w-16 h-16 text-red-500 mx-auto" />
                      </motion.div>
                      <h3 className="text-xl font-bold text-red-600 mb-2">Not quite!</h3>
                      <p className="text-muted-foreground">
                        The answer was: <span className="font-medium">{lastResult.correctAnswer}</span>
                      </p>
                    </>
                  )}
                  
                  <Button 
                    onClick={nextRiddle}
                    className="mt-6 bg-purple-600 hover:bg-purple-700"
                  >
                    {currentRiddleIndex < riddles.length - 1 ? (
                      <>Next Riddle <ChevronRight className="w-4 h-4 ml-1" /></>
                    ) : (
                      "See Results"
                    )}
                  </Button>
                </motion.div>
              ) : currentRiddle && (
                <motion.div
                  key={currentRiddle.id}
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                >
                  <Card className="bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 border-purple-200 dark:border-purple-800">
                    <CardContent className="pt-6">
                      <div className="flex items-start gap-3 mb-4">
                        <div className="text-3xl">🤔</div>
                        <div>
                          <p className="text-xs text-purple-600 dark:text-purple-400 font-medium mb-1">Who Am I?</p>
                          <p className="text-lg font-medium italic leading-relaxed">
                            "{currentRiddle.riddleText}"
                          </p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>

                  {hasAttempted ? (
                    <div className="mt-6 text-center">
                      <p className="text-muted-foreground mb-2">
                        You already answered this riddle
                      </p>
                      <p className="font-medium">
                        Your answer: <span className={currentAttempt?.isCorrect ? "text-green-600" : "text-red-600"}>
                          {currentAttempt?.selectedAnswer}
                        </span>
                        {currentAttempt?.isCorrect ? (
                          <Check className="w-4 h-4 inline ml-1 text-green-600" />
                        ) : (
                          <X className="w-4 h-4 inline ml-1 text-red-600" />
                        )}
                      </p>
                      <Button 
                        onClick={nextRiddle}
                        className="mt-4"
                        variant="outline"
                      >
                        {currentRiddleIndex < riddles.length - 1 ? "Next Riddle" : "See Results"}
                      </Button>
                    </div>
                  ) : (
                    <div className="mt-6 space-y-3">
                      {(currentRiddle.answerOptions as string[]).map((option, i) => (
                        <motion.button
                          key={i}
                          whileHover={{ scale: 1.02 }}
                          whileTap={{ scale: 0.98 }}
                          onClick={() => setSelectedAnswer(option)}
                          className={`w-full p-4 rounded-lg border-2 text-left transition-all ${
                            selectedAnswer === option
                              ? "border-purple-500 bg-purple-50 dark:bg-purple-900/30"
                              : "border-gray-200 dark:border-gray-700 hover:border-purple-300"
                          }`}
                          data-testid={`button-answer-option-${i}`}
                        >
                          <div className="flex items-center gap-3">
                            <MapPin className="w-5 h-5 text-purple-500 flex-shrink-0" />
                            <span className="font-medium">{option}</span>
                          </div>
                        </motion.button>
                      ))}
                      
                      <Button
                        onClick={submitAnswer}
                        disabled={!selectedAnswer || isSubmitting}
                        className="w-full mt-4 bg-purple-600 hover:bg-purple-700"
                        data-testid="button-submit-answer"
                      >
                        {isSubmitting ? "Checking..." : "Submit Answer"}
                      </Button>
                    </div>
                  )}
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}

interface TrailTalesPopupProps {
  tripId: string;
  riddle: TrailTalesRiddle;
  onClose: () => void;
  onAnswer: (isCorrect: boolean) => void;
}

export function TrailTalesPopup({ tripId, riddle, onClose, onAnswer }: TrailTalesPopupProps) {
  const { activeExplorer } = useExplorer();
  const [selectedAnswer, setSelectedAnswer] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [result, setResult] = useState<{ isCorrect: boolean; starsEarned: number } | null>(null);

  const submitAnswer = async () => {
    if (!selectedAnswer || !activeExplorer) return;
    
    setIsSubmitting(true);
    try {
      const res = await apiRequest("POST", `/api/travel/trail-tales/riddles/${riddle.id}/answer`, {
        explorerId: activeExplorer.id,
        selectedAnswer
      });
      
      const data = await res.json();
      setResult({
        isCorrect: data.isCorrect,
        starsEarned: data.starsEarned
      });
      
      if (data.isCorrect) {
        confetti({
          particleCount: 30,
          spread: 50,
          origin: { y: 0.7 }
        });
      }
      
      setTimeout(() => {
        onAnswer(data.isCorrect);
        onClose();
      }, 2000);
      
    } catch (error) {
      console.error("Error submitting answer:", error);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 50 }}
      className="fixed inset-x-4 bottom-24 z-50 md:inset-x-auto md:left-1/2 md:-translate-x-1/2 md:w-96"
    >
      <Card className="bg-gradient-to-br from-purple-500 to-indigo-600 text-white shadow-xl border-0">
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center gap-2 text-lg">
            <Brain className="w-5 h-5" />
            Trail Tales Challenge!
          </CardTitle>
        </CardHeader>
        <CardContent>
          {result ? (
            <motion.div
              initial={{ scale: 0.8 }}
              animate={{ scale: 1 }}
              className="text-center py-4"
            >
              {result.isCorrect ? (
                <>
                  <Check className="w-12 h-12 mx-auto mb-2" />
                  <p className="font-bold text-lg">Correct!</p>
                  <div className="flex justify-center gap-1 mt-2">
                    {Array.from({ length: result.starsEarned }).map((_, i) => (
                      <Star key={i} className="w-6 h-6 text-yellow-300 fill-yellow-300" />
                    ))}
                  </div>
                </>
              ) : (
                <>
                  <X className="w-12 h-12 mx-auto mb-2" />
                  <p className="font-bold text-lg">Not quite!</p>
                  <p className="text-sm opacity-80">The answer was {riddle.answer}</p>
                </>
              )}
            </motion.div>
          ) : (
            <>
              <p className="text-white/90 mb-4 italic">"{riddle.riddleText}"</p>
              
              <div className="space-y-2">
                {(riddle.answerOptions as string[]).map((option, i) => (
                  <button
                    key={i}
                    onClick={() => setSelectedAnswer(option)}
                    className={`w-full p-3 rounded-lg text-left transition-all ${
                      selectedAnswer === option
                        ? "bg-white text-purple-600"
                        : "bg-white/20 hover:bg-white/30"
                    }`}
                  >
                    {option}
                  </button>
                ))}
              </div>
              
              <div className="flex gap-2 mt-4">
                <Button
                  variant="ghost"
                  onClick={onClose}
                  className="flex-1 text-white hover:bg-white/20"
                >
                  Skip
                </Button>
                <Button
                  onClick={submitAnswer}
                  disabled={!selectedAnswer || isSubmitting}
                  className="flex-1 bg-white text-purple-600 hover:bg-white/90"
                >
                  Answer
                </Button>
              </div>
            </>
          )}
        </CardContent>
      </Card>
    </motion.div>
  );
}
