export const G = {
  orange: '#E8692A',
  oLt: '#FDF0E9',
  oDk: '#C4561E',
  bg: '#F5F2EE',
  card: '#FFFFFF',
  deep: '#1A1F2E',
  muted: '#8A8FA8',
  sage: '#7A9E8E',
  sageLt: '#EEF5F2',
  amber: '#F5A623',
  amberBg: '#FFF8EC',
  green: '#3DAA6E',
} as const;

export const F = {
  regular: 'PlusJakartaSans_400Regular',
  medium: 'PlusJakartaSans_500Medium',
  semibold: 'PlusJakartaSans_600SemiBold',
  bold: 'PlusJakartaSans_700Bold',
} as const;

export const CHIP_COLORS = [G.orange, G.sage, G.amber, '#E86A9A', '#7B6FE8'] as const;

// Cities with pre-seeded data in the GeoAdventures backend
export type CityEntry = { name: string; country: string; state?: string };

export const POPULAR_CITIES: CityEntry[] = [
  { name: 'Chicago', country: 'USA', state: 'Illinois' },
  { name: 'New York', country: 'USA', state: 'New York' },
  { name: 'San Francisco', country: 'USA', state: 'California' },
  { name: 'Los Angeles', country: 'USA', state: 'California' },
  { name: 'Washington DC', country: 'USA', state: 'DC' },
  { name: 'Boston', country: 'USA', state: 'Massachusetts' },
];

export const ALL_CITIES: CityEntry[] = [
  // USA — pre-seeded
  { name: 'Chicago', country: 'USA', state: 'Illinois' },
  { name: 'New York', country: 'USA', state: 'New York' },
  { name: 'San Francisco', country: 'USA', state: 'California' },
  { name: 'Los Angeles', country: 'USA', state: 'California' },
  { name: 'Washington DC', country: 'USA', state: 'DC' },
  { name: 'Boston', country: 'USA', state: 'Massachusetts' },
  { name: 'Seattle', country: 'USA', state: 'Washington' },
  { name: 'Miami', country: 'USA', state: 'Florida' },
  { name: 'Orlando', country: 'USA', state: 'Florida' },
  { name: 'Nashville', country: 'USA', state: 'Tennessee' },
  { name: 'New Orleans', country: 'USA', state: 'Louisiana' },
  { name: 'Denver', country: 'USA', state: 'Colorado' },
  { name: 'Austin', country: 'USA', state: 'Texas' },
  { name: 'Dallas', country: 'USA', state: 'Texas' },
  { name: 'Houston', country: 'USA', state: 'Texas' },
  { name: 'Phoenix', country: 'USA', state: 'Arizona' },
  { name: 'Las Vegas', country: 'USA', state: 'Nevada' },
  { name: 'Portland', country: 'USA', state: 'Oregon' },
  { name: 'Minneapolis', country: 'USA', state: 'Minnesota' },
  { name: 'Philadelphia', country: 'USA', state: 'Pennsylvania' },
  { name: 'Atlanta', country: 'USA', state: 'Georgia' },
  { name: 'Charlotte', country: 'USA', state: 'North Carolina' },
  { name: 'Raleigh', country: 'USA', state: 'North Carolina' },
  { name: 'Detroit', country: 'USA', state: 'Michigan' },
  { name: 'Indianapolis', country: 'USA', state: 'Indiana' },
  { name: 'Columbus', country: 'USA', state: 'Ohio' },
  { name: 'Cleveland', country: 'USA', state: 'Ohio' },
  { name: 'Pittsburgh', country: 'USA', state: 'Pennsylvania' },
  { name: 'St. Louis', country: 'USA', state: 'Missouri' },
  { name: 'Saint Louis', country: 'USA', state: 'Missouri' },
  { name: 'Kansas City', country: 'USA', state: 'Missouri' },
  { name: 'Salt Lake City', country: 'USA', state: 'Utah' },
  { name: 'San Diego', country: 'USA', state: 'California' },
  { name: 'Sacramento', country: 'USA', state: 'California' },
  { name: 'San Antonio', country: 'USA', state: 'Texas' },
  { name: 'Tampa', country: 'USA', state: 'Florida' },
  { name: 'Baltimore', country: 'USA', state: 'Maryland' },
  { name: 'Milwaukee', country: 'USA', state: 'Wisconsin' },
  { name: 'Louisville', country: 'USA', state: 'Kentucky' },
  { name: 'Memphis', country: 'USA', state: 'Tennessee' },
  { name: 'Richmond', country: 'USA', state: 'Virginia' },
  { name: 'Savannah', country: 'USA', state: 'Georgia' },
  { name: 'Charleston', country: 'USA', state: 'South Carolina' },
  { name: 'Asheville', country: 'USA', state: 'North Carolina' },
  { name: 'Santa Fe', country: 'USA', state: 'New Mexico' },
  { name: 'Albuquerque', country: 'USA', state: 'New Mexico' },
  { name: 'Tucson', country: 'USA', state: 'Arizona' },
  { name: 'Scottsdale', country: 'USA', state: 'Arizona' },
  { name: 'Boise', country: 'USA', state: 'Idaho' },
  { name: 'Anchorage', country: 'USA', state: 'Alaska' },
  { name: 'Honolulu', country: 'USA', state: 'Hawaii' },
  { name: 'Maui', country: 'USA', state: 'Hawaii' },
  { name: 'San Jose', country: 'USA', state: 'California' },
  { name: 'Oakland', country: 'USA', state: 'California' },
  { name: 'Monterey', country: 'USA', state: 'California' },
  { name: 'Santa Barbara', country: 'USA', state: 'California' },
  { name: 'Napa', country: 'USA', state: 'California' },
  { name: 'Sedona', country: 'USA', state: 'Arizona' },
  { name: 'Park City', country: 'USA', state: 'Utah' },
  { name: 'Jackson Hole', country: 'USA', state: 'Wyoming' },
  { name: 'Yellowstone', country: 'USA', state: 'Wyoming' },
  { name: 'Grand Canyon', country: 'USA', state: 'Arizona' },
  { name: 'Glacier National Park', country: 'USA', state: 'Montana' },
  { name: 'Yosemite', country: 'USA', state: 'California' },
  // International
  { name: 'London', country: 'UK' },
  { name: 'Paris', country: 'France' },
  { name: 'Rome', country: 'Italy' },
  { name: 'Barcelona', country: 'Spain' },
  { name: 'Amsterdam', country: 'Netherlands' },
  { name: 'Dublin', country: 'Ireland' },
  { name: 'Edinburgh', country: 'UK' },
  { name: 'Lisbon', country: 'Portugal' },
  { name: 'Prague', country: 'Czech Republic' },
  { name: 'Vienna', country: 'Austria' },
  { name: 'Tokyo', country: 'Japan' },
  { name: 'Kyoto', country: 'Japan' },
  { name: 'Sydney', country: 'Australia' },
  { name: 'Melbourne', country: 'Australia' },
  { name: 'Toronto', country: 'Canada' },
  { name: 'Vancouver', country: 'Canada' },
  { name: 'Montreal', country: 'Canada' },
  { name: 'Mexico City', country: 'Mexico' },
  { name: 'Cancun', country: 'Mexico' },
];

export const CITY_COUNTRY: Record<string, string> = Object.fromEntries(
  ALL_CITIES.map(c => [c.name, c.country])
);

export const CITY_IMGS: Record<string, string> = {
  Chicago: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400&q=80',
  'New York': 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=400&q=80',
  Tokyo: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400&q=80',
  Rome: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400&q=80',
  London: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400&q=80',
  'San Francisco': 'https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=400&q=80',
  'Los Angeles': 'https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=400&q=80',
  'Washington DC': 'https://images.unsplash.com/photo-1501466044931-62695aada8e9?w=400&q=80',
  Boston: 'https://images.unsplash.com/photo-1501979376754-f3e48ddb95e8?w=400&q=80',
  Miami: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&q=80',
  Orlando: 'https://images.unsplash.com/photo-1580835239846-5e3c8a83e0a7?w=400&q=80',
  Nashville: 'https://images.unsplash.com/photo-1611416518757-e98aacede46e?w=400&q=80',
  Seattle: 'https://images.unsplash.com/photo-1502175353174-a7a70e73b362?w=400&q=80',
  Denver: 'https://images.unsplash.com/photo-1583001809873-a128495da465?w=400&q=80',
  Austin: 'https://images.unsplash.com/photo-1531218150217-54595bc2b934?w=400&q=80',
  Paris: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&q=80',
  Barcelona: 'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=400&q=80',
  Amsterdam: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=400&q=80',
  Sydney: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=400&q=80',
  Toronto: 'https://images.unsplash.com/photo-1517935706615-2717063c2225?w=400&q=80',
  'Las Vegas': 'https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=400&q=80',
  'New Orleans': 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&q=80',
  Honolulu: 'https://images.unsplash.com/photo-1542259009477-d625272157b7?w=400&q=80',
  Kyoto: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400&q=80',
};

export const CITY_COORDS: Record<string, { lat: number; lon: number }> = {
  'Chicago': { lat: 41.85, lon: -87.65 },
  'Saint Louis': { lat: 38.63, lon: -90.20 },
  'St. Louis': { lat: 38.63, lon: -90.20 },
  'New York': { lat: 40.71, lon: -74.01 },
  'San Francisco': { lat: 37.77, lon: -122.42 },
  'Los Angeles': { lat: 34.05, lon: -118.24 },
  'Washington DC': { lat: 38.91, lon: -77.04 },
  'Boston': { lat: 42.36, lon: -71.06 },
  'Miami': { lat: 25.77, lon: -80.19 },
  'Seattle': { lat: 47.61, lon: -122.33 },
  'Denver': { lat: 39.74, lon: -104.99 },
  'Nashville': { lat: 36.17, lon: -86.78 },
  'Austin': { lat: 30.27, lon: -97.74 },
  'Dallas': { lat: 32.78, lon: -96.80 },
  'Houston': { lat: 29.76, lon: -95.37 },
  'New Orleans': { lat: 29.95, lon: -90.07 },
  'Atlanta': { lat: 33.75, lon: -84.39 },
  'Phoenix': { lat: 33.45, lon: -112.07 },
  'Las Vegas': { lat: 36.17, lon: -115.14 },
  'Minneapolis': { lat: 44.98, lon: -93.27 },
  'Portland': { lat: 45.52, lon: -122.68 },
  'Salt Lake City': { lat: 40.76, lon: -111.89 },
  'Kansas City': { lat: 39.10, lon: -94.58 },
  'Philadelphia': { lat: 39.95, lon: -75.16 },
  'Indianapolis': { lat: 39.77, lon: -86.16 },
  'Columbus': { lat: 39.96, lon: -83.00 },
  'Detroit': { lat: 42.33, lon: -83.05 },
  'Charlotte': { lat: 35.23, lon: -80.84 },
  'Milwaukee': { lat: 43.04, lon: -87.91 },
  'Louisville': { lat: 38.25, lon: -85.76 },
  'Memphis': { lat: 35.15, lon: -90.05 },
  'San Diego': { lat: 32.72, lon: -117.16 },
  'San Antonio': { lat: 29.42, lon: -98.49 },
  'Tampa': { lat: 27.95, lon: -82.46 },
  'Orlando': { lat: 28.54, lon: -81.38 },
  'Honolulu': { lat: 21.31, lon: -157.86 },
  'Savannah': { lat: 32.08, lon: -81.10 },
  'Charleston': { lat: 32.78, lon: -79.94 },
  'Asheville': { lat: 35.59, lon: -82.55 },
  'Santa Fe': { lat: 35.69, lon: -105.94 },
  'Sedona': { lat: 34.87, lon: -111.76 },
  'Park City': { lat: 40.65, lon: -111.50 },
  'Jackson Hole': { lat: 43.48, lon: -110.76 },
  'Boise': { lat: 43.62, lon: -116.20 },
  'Raleigh': { lat: 35.78, lon: -78.64 },
  'Richmond': { lat: 37.54, lon: -77.44 },
  'Baltimore': { lat: 39.29, lon: -76.61 },
  'Pittsburgh': { lat: 40.44, lon: -80.00 },
  'Cleveland': { lat: 41.50, lon: -81.69 },
  'Anchorage': { lat: 61.22, lon: -149.90 },
};

export function haversineKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a = Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon / 2) ** 2;
  return Math.round(R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)));
}

export const STYLE_MAP: Record<string, string> = {
  highlights: 'iconic_highlights',
  balanced: 'family_explorer',
  offbeat: 'city_explorer',
  easy: 'family_explorer',
};

export const PACE_MAP: Record<string, string> = {
  relaxed: 'chill',
  moderate: 'balanced',
  busy: 'packed',
};
