// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/travel-cards/AccentStrip.tsx": () => import("../components/mockups/travel-cards/AccentStrip.tsx"),
  "./components/mockups/travel-cards/DarkNight.tsx": () => import("../components/mockups/travel-cards/DarkNight.tsx"),
  "./components/mockups/travel-cards/FlatRow.tsx": () => import("../components/mockups/travel-cards/FlatRow.tsx"),
  "./components/mockups/travel-cards/PillChip.tsx": () => import("../components/mockups/travel-cards/PillChip.tsx"),
  "./components/mockups/travel-cards/VividPlay.tsx": () => import("../components/mockups/travel-cards/VividPlay.tsx"),
  "./components/mockups/travel-cards/WarmJournal.tsx": () => import("../components/mockups/travel-cards/WarmJournal.tsx")
};
